### ISSUE TITLE
Android Studio doesen't track small amount of times

### ISSUE THREAD

**Issue by Cataalinn** [wakatime/wakatime#100]
Today i was made a small change (under 5 minutes) into one project, like changing a row and then closed the project. That time was not recordered.

**Update**

Nevermind. If i set a higher timeout threshold, time is recorded. You can close this issue.

**Comment by alanhamlett** [comment]
What's your [timeout setting](https://wakatime.com/faq#accuracy) set to?

**Comment by Cataalinn** [comment]
Initially was set to 10 minutes. Now i put it on 40 minutes in order to see that modification under 5 minutes. Weird.
