### ISSUE TITLE
Wakatime API Maintenance

### ISSUE THREAD

**Issue by int0x01** [wakatime/wakatime#111]
Firstly - thank you for building Wakatime. I've been trying to increasingly use it where I can, as it has made a major positive impact on my productivity.

I noticed that from 11-17 8 AM PST to today (11-19 2PM PST) that my local data has not been showing up on the dashboard. Digging into the logs, I'm noticing a fair number of warning logs with the following stringified json in the `messages` key:

```
{
  'response_code': 500, 
  'response_content': '{\\n  \"error\": \"API Maintenance. Please try again later.\"\\n}\\n'}"
}

```

Just wanted to confirm that this is linked to the message on the dashboard:

>Note: We are experiencing degraded performance. Dashboards may show missing or no coding activity, but your coding activity is saved locally and will be synced once our processing catches up with the incoming data.

Thanks!

**Comment by alanhamlett** [comment]
The API should be responding with success codes now, but your dashboard and leaderboards will take a while to show recent coding activity.

**Comment by int0x01** [comment]
Just wanted to leave a comment that syncing has started working again today (for me, anyway)! I'll close this issue.
