### ISSUE TITLE
How can i track changes only inside my work folder ?

### ISSUE THREAD

**Issue by georoot** [wakatime/wakatime#117]
The current configuration that i am using is

```
[settings]
debug = false
hidefilenames = false
ignore =
    COMMIT_EDITMSG$
    PULLREQ_EDITMSG$
    MERGE_MSG$
    TAG_EDITMSG$
include=
    /home/user/Work/*
```

I only want to track changes made inside `Work` directory but it ends up tracking everything. What is the right way to do that ?

**Comment by alanhamlett** [comment]
Change your config to this:

```
[settings]
debug = false
hidefilenames = false
ignore =
    COMMIT_EDITMSG$
    PULLREQ_EDITMSG$
    MERGE_MSG$
    TAG_EDITMSG$
    .*
include=
    /home/user/Work/*
```

That excludes/ignores everything, then only selectively includes your work folder.

**Comment by georoot** [comment]
Thanks for the instant reply.
