### ISSUE TITLE
pygments3 is installed when I have python 2.7

### ISSUE THREAD

**Issue by ProjectFrank** [wakatime/wakatime#12]
Hi,

I tried to install wakatime on the OSX10.9.4 default python and got some compilation errors.

I then installed a homebrewed python and got similar errors.

      File "/usr/local/lib/python2.7/site-packages/wakatime/packages/pygments3/pygments/style.py", line 107
        class Style(object, metaclass=StyleMeta):
                                     ^
    SyntaxError: invalid syntax

I suspect that the pygments3 package is only for python3.  How can I install properly?  Further, why does wakatime need pygments?

**Comment by alanhamlett** [comment]
Looks like the error message is gone in the latest version of the wakatime package on pypi, so closing this issue.
