### ISSUE TITLE
Feature Request: Categorize *.mjs files as JavaScript

### ISSUE THREAD

**Issue by StephenKoller** [wakatime/wakatime#121]
Wakatime currently categorizes edits occurring in ES6 *.mjs files as language "Other".

![image](https://user-images.githubusercontent.com/1561673/35815457-876ad5f6-0a66-11e8-8116-3cb362f24a3b.png)

Would like to see *.mjs categorized as JavaScript.

**Comment by alanhamlett** [comment]
Fixed with 218141217aac4b9ad477a8b686f34c432d293082.
