### ISSUE TITLE
wakatime does't work

### ISSUE THREAD

**Issue by miaobrother** [wakatime/wakatime#123]
I am so sorry, i am trying to provide my english , my IDES pycharm and GoLand install wakatime does't work , i want it do work ,Please help me!

**Comment by alanhamlett** [comment]
Can you please open a new issue on the Jetbrains repo, and I will help there:

https://github.com/wakatime/jetbrains-wakatime/issues/new

Please also turn on [DEBUG mode](https://github.com/wakatime/jetbrains-wakatime/#troubleshooting) and copy/paste any error messages into the issue you create.
