### ISSUE TITLE
Wakatime for PowerShell

### ISSUE THREAD

**Issue by mpearon** [wakatime/wakatime#126]
Is there any consideration being put into developing a plugin for PowerShell like there is for Terminal?
I saw that @irondoge spun one up for Bash.  I've been playing around with the API a bit, but I haven't had any luck getting this to add entries to my dashboard:

`
wakatime --write --plugin 'PowerShell Console' --entity-type 'file' --entity 'C:\temp\wakatest.ps1' --project 'Miscellaneous' --hostname "$env:COMPUTERNAME"
`

There isn't a native plugin architecture for PowerShell - you could leverage modules, though.
Worst case, the prompt function could be overloaded like he's done in his bash implementation.

**Comment by mpearon** [comment]
@alanhamlett - Possibly this one too?

**Comment by irondoge** [comment]
Hi, I will take a look at it soon because unfortunately, I don't have much time right now, but I think your suggestion about overloading the prompt function is the right way to do it, I mean if you find a way to keep the execution of the default prompt function right after your custom one.
Regards

**Comment by iamkarlson** [comment]
Hi, there's a posh git plugin for powershell which does exactly like you said: it overrides default promt with some cool things like git stats. Maybe it's somehow possible to use?

**Comment by iamkarlson** [comment]
Here's my version of very simple heartbeat from the powershell:

```Powershell

$wakatime = $(where.exe wakatime);
function global:prompt {

    if($wakatime) {
        wakatime --entity-type app --project Powershell;
    }

    return "=]"
}

```
Put this line in your $Profile. Usually it's here :
```
C:\Users\user_name\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
```

before that 

```
pip install wakatime
```

**Comment by mpearon** [comment]
Thanks, @iamkarlson!  I'll take a look at this later on today.

**Comment by iamkarlson** [comment]
@mpearon I've played a bit with stuff around and put in the repo [here](https://github.com/iamkarlson/powerwaka). Give it a try when you have time.

**Comment by mpearon** [comment]
So, @iamkarlson - I completely forgot to get back to you to let you know that I was able to get something sorted based on your repo. :)  Thank you for the assistance!

**Comment by Gravifer** [comment]
I gathered the code by @iamkarlson @mpearon et al. in related threads, and pushed a module named posh-wakatime to the PSGallery. It is still at an early stage, and any help is welcome at the repo. I haven't sort out the contribution yet, and copyright informations need to be updated, too.
