### ISSUE TITLE
Missing languages and editors legend 

### ISSUE THREAD

**Issue by AlexandruBuhai** [wakatime/wakatime#132]
First, thanks for making this software, it's great!
Sorry if this is duplicate or if this is not the place to ask the question, feel free to delete if that is so.

I seem to be missing the legend that tells me what color is what IDE and Languages in the pie graphs. 
![wakatime](https://user-images.githubusercontent.com/23296075/39014568-63c96a4e-4423-11e8-8612-705f8c11f21c.png)  
It was there the first days I used the application, but now it is gone. 
Is it because of the fact that it registered too many languages/file extensions?

Thanks in advance!

**Comment by alanhamlett** [comment]
The legend is disabled with many languages, because it doesn't fit on the screen.

**Comment by AlexandruBuhai** [comment]
And how can i remove some of my languages?

**Comment by alanhamlett** [comment]
You could rename them with Custom Rules:
https://wakatime.com/settings/rules

**Comment by AlexandruBuhai** [comment]
Thanks for the answer, I managed to get it back after adding some of rules. You can consider the Issue solved.

**Comment by alanhamlett** [comment]
Ok, thanks for circling back!
