### ISSUE TITLE
only_include_with_project_file setting not respected

### ISSUE THREAD

**Issue by derekjamescurtis** [wakatime/wakatime#140]
I'm not sure if this is a bug, or I'm just misunderstanding what this setting is supposed to do. 

I assume that the only_include_with_project_file = true should only send data to wakatime **if** there is a .wakatime-project file present.

my .wakatime.cfg file

```ini
[settings]
api_key = MY_API_KEY
only_include_with_project_file = true
```

Then, I create one project with the .wakatime-project file, which works properly and overrides the project name with the one I've specified.

<img width="525" alt="should-track" src="https://user-images.githubusercontent.com/1916761/41275808-50446c28-6e4c-11e8-9ae4-a61dc3224f7b.png">

In my second project, the project is still reported with the directory name as the project name.  

<img width="695" alt="should-not-track" src="https://user-images.githubusercontent.com/1916761/41275803-4ad16e58-6e4c-11e8-9a3a-ce24f9557410.png">

I expect only Qardisc Admin/API to show in my projects list, but I see both projects.

<img width="914" alt="project-list" src="https://user-images.githubusercontent.com/1916761/41275791-432b0bf0-6e4c-11e8-8017-7039550a1a6c.png">

What exactly is the **only_include_with_project_file** supposed to do?  

Thanks

**Comment by alanhamlett** [comment]
When looking at [this chart](https://wakatime.com/dashboard/day?date=2018-06-12), is the coding activity still being tracked *after* you added the `only_include_with_project_file` setting? If the project was created before adding that setting, then it won't be deleted... it just won't show up in future coding activity.

**Comment by derekjamescurtis** [comment]
@alanhamlett Yes.  I have confirmed that on the above-linked chart, the project is **still** being tracked.

Some additional information:

This problem is occurring on two different machines, using two different IDE plugins.

- MacOS (10.13.5) running PyCharm with the most-recent version of the wakatime plugin.  Wakatime cli is version 10.2.1
- MacOS (10.13.5) running the XCode wakatime plugin (installed fresh today)

This problem occurred today as I was helping one of our developers get this setup on their machine so we can begin using waktime teams.  He wants to keep some of his personal projects from being recorded in wakatime.

**Comment by alanhamlett** [comment]
Oh, sorry about this. The example config had a typo. Using this config should work:

```ini
[settings]
api_key = XXX
include_only_with_project_file = true
```
