### ISSUE TITLE
Use rules to rename "Unknown Project"

### ISSUE THREAD

**Issue by Xunnamius** [wakatime/wakatime#146]
Is there some way to rename the "Unknown Project" placeholder to something else? All of my projects and activity are in lower case so I wanted to change this text to match. Thanks.

**Comment by alanhamlett** [comment]
Here are different ways to rename projects:
https://wakatime.com/faq#rename-projects

**Comment by Xunnamius** [comment]
@alanhamlett I tried this, but it doesn't seem to work. See screenshots below:

![2018-09-15 3](https://user-images.githubusercontent.com/656017/45592856-93961e80-b93e-11e8-8f53-c865b941c96d.png)

![2018-09-15 4](https://user-images.githubusercontent.com/656017/45592857-96910f00-b93e-11e8-95a9-8d77477510ba.png)

I literally want to rename "Unknown Project" to be a different placeholder for unknown projects than the default "Unknown Project". I'd like it to say `[miscellaneous]` whenever an unknown project is encountered instead, since that conforms to all the other "catch all" project types I've defined via custom rules (i.e. `[chrome/browser]` for my terminal activity and `[chrome/browser]` for my browser activity).

I don't think it's currently possible, but it'd be really nice :)

**Comment by alanhamlett** [comment]
Oh, since `Unknown Project` is actually null it's not able to match. I'll look into a special case for matching null as `Unknown Project` and update here with a solution.

**Comment by PlumbBum** [comment]
Hi @alanhamlett , any luck with this? I'm trying to define the 'Unknown Project' I've been working on for the past week or so using the rules feature however am unable to due to the issue detailed above.

Cheers.

**Comment by Destaq** [comment]
@alanhamlett Any update? I'd be really interested in this feature, and it doesn't make sense to create folders for random files opened on Desktop, random folders, etc.

Even just renaming to miscellaneous would be nice.

**Comment by c3r38r170** [comment]
Have you tried SpiderMonkey or any other script executor? It is a downside if you access from multiple devices / browsers to add the extension to them all but at least it's a solution.
I think this is a rather good solution as the change is just superficial and can be just done in the frontend.

**Comment by alanhamlett** [comment]
I think allowing a rule to match empty/unknown project promotes using Custom Rules the wrong way. Instead, match the file path to set a project name as that won't incorrectly move activity into the wrong project.

At the most, we would add a user preference to change `Unknown Project` into something else but the effort required to support this isn't realistic. We won't be fixing this one.
