### ISSUE TITLE
Documentation/clarification request: what does this part of the web UI mean?

### ISSUE THREAD

**Issue by Xunnamius** [wakatime/wakatime#147]
Sorry if this has been explained elsewhere, but what does this mean?

![2018-09-15 5](https://user-images.githubusercontent.com/656017/45592936-34390e00-b940-11e8-8d3c-232c2a3e8cfb.png)

Specifically, 100% *of what*? Does this mean I met the goal I set for today? And then 55% increase over what? My daily average? Yesterday's logged time?

Perhaps an addition to the FAQ is in order?

Also, I'm seeking some clarification on the execution order of the custom rules. **Are the custom transformation rules applied in parallel?** Using my custom rules as an example, that'd mean the projects that start with `Terminal` that I transform into `[hyper/terminal]` would not be noticed by the rules below it that are simultaneously looking for projects that already start with `[hyper/terminal]`. **Are the rules applied in sequence?** In this case, a rule wouldn't run until the rule above it finishes executing. I suspect the latter, but, just to be safe, I always make two passes (press "save" twice) to ensure the rules are applied consistently across my data and nothing gets corrupted.

Thanks!

**Comment by alanhamlett** [comment]
That half-donut chart shows your progress for the last day in the current dashboard range compared against all the days in the current dashboard range. For your screenshot that means:

55% increase Today compared to a daily average of 7hrs 59 mins over the last 14 days.

> Also, I'm seeking some clarification on the execution order of the custom rules.

Custom rules are applied sequentially to future and past activity, so yes a rule wouldn't run until the rule above it finishes executing.
