### ISSUE TITLE
Code Delete Tool not working

### ISSUE THREAD

**Issue by WrongWay** [wakatime/wakatime#148]
Removing heartbeats in Code Delete Tool does not work. After refreshing the page they are still there, although the DELETE request being successfully executed and server responding with 200 status.

**UPD** It worked on the fifth time. Maybe the delete process is delayed? If so, the tool should warn about that.

**Comment by alanhamlett** [comment]
That api endpoint for reading heartbeats was cached recently, I'll turn off caching so this won't happen again.
