### ISSUE TITLE
Custom rules are not working

### ISSUE THREAD

**Issue by Xunnamius** [wakatime/wakatime#150]
My custom rules look like this:

![2018-10-11 1](https://user-images.githubusercontent.com/656017/46829682-050d9500-cd64-11e8-8c0d-b974cd459b0a.png)

Two things are happening that shouldn't.

**1. Nothing is being categorized as `debugging` despite my custom rules**

Everything is being marked as either `coding` or `browsing`, in direct contradiction to my custom rules. Specifically, my final custom rule should be changing all `[hyper/terminal]` project activity to the `debugging` category, but this is not happening at all. It stopped categorizing them properly somewhat recently. Worse, I remember seeing a lot more of my activity categorized as `debugging`, but all file categories after mid September seem to have been changed to `coding` or `browsing`... perhaps due to a regression in the application or a misbehaving plugin?

![2018-10-11 4](https://user-images.githubusercontent.com/656017/46829747-3be3ab00-cd64-11e8-9d1b-b7fab1ada6f7.png)

**2. Files that are URLs are being mishandled and the custom rules governing them are being ignored**

Given my custom rules, something like this should NOT be happening. Note that the `[hyper/terminal]` project (below) should also have all of its files categorized as `debugging` by the custom rules but that is not happening.

![2018-10-11 2](https://user-images.githubusercontent.com/656017/46830033-1a36f380-cd65-11e8-99fa-cbf4a9d53c15.png)

![2018-10-11 3](https://user-images.githubusercontent.com/656017/46830029-173c0300-cd65-11e8-8560-9a285faf8361.png)

Please advise. Thanks!

**Comment by alanhamlett** [comment]
We've recently improved [Custom Rules](https://wakatime.com/settings/rules) to better match App/Terminal and Url/Domain stats types.
