### ISSUE TITLE
Feature Request: New category "Writing Tests"

### ISSUE THREAD

**Issue by TaDe90** [wakatime/wakatime#156]
I want to distinguish the time I spend writing production code and test code.

At the moment I have configured custom rules to get the distinction:
![image](https://user-images.githubusercontent.com/2879214/49405729-93463c00-f753-11e8-80e4-5b8fe37904d8.png)
These rules follow the conventions for test files in C# and TypeScript.

Unfortunately, there is no category for writing tests.
So, I'm requesting a new category "Writing Tests".

**Comment by alanhamlett** [comment]
Added with 2599beba9c1de086bd76c7acea187ee8421626f1 and released with v10.5.0.

**Comment by TaDe90** [comment]
@alanhamlett Wow. The second time in one week you respond to my request within one day and fix the problem/implement the feature. Just amazing. Keep the good work up. :D
