### ISSUE TITLE
How can i force sync all my coding activity?

### ISSUE THREAD

**Issue by NikosEfthias** [wakatime/wakatime#157]
Sometimes wakatime service goes down or sometimes i code offline is there a way to force sync my local database when im online ?

**Comment by alanhamlett** [comment]
Running this command to install the wakatime cli:
`sudo pip install --upgrade wakatime`
Then run this command to sync up to 9999 heartbeats of coding activity:
`wakatime --sync-offline-activity 9999`

**Comment by NikosEfthias** [comment]
thank you
