### ISSUE TITLE
SSMS Plugin no longer supported?

### ISSUE THREAD

**Issue by frackham** [wakatime/wakatime#158]
_Apologies, I can't see where to raise this as there's no contact mechanism on the site, and the open issues in the plugin itself don't have any recent responses._

Any intention of removing SSMS from the list of supported plugins, as 2016 onwards can't be used (not plugin author's fault, as SSMS plugin structure has changed)?

https://github.com/gandarez/ssms-wakatime

**Comment by gandarez** [comment]
Just released a new version to support v2012+

Download and follow the instructions
https://github.com/gandarez/ssms-wakatime/releases/tag/v2.0.0
