### ISSUE TITLE
Hide WakaTime Status from Status Bar

### ISSUE THREAD

**Issue by wesbos** [wakatime/wakatime#16]
The Statusbar in Sublime Text is pretty coveted space and many plugins have to fight for space in it.

I love wakatime, but its really passive for me so I don't necessarily care about the status of wakatime at all times.

Is there anyway to hide this? I much rather save the space for my wordcount and git status.

**Comment by sisou** [comment]
There's a setting for it, as can be seen in Sublime in `Preferences -> WakaTime -> Settings - Default`. You can add this to your User preference file:
``` 
    // Status bar message. Set to false to hide status bar message.
    // Defaults to true.
    "status_bar_message": true
```

**Comment by wesbos** [comment]
Exactly what I was looking for - thanks!
