### ISSUE TITLE
Option to use System Certificate Store

### ISSUE THREAD

**Issue by will7200** [wakatime/wakatime#164]
### Requests Certificates
Due to wakatime using requests internally for web requests, it uses a bundled ca as opposed to using a system specified certificate store.

### Propose
I would be nice to have an option to use a specified ca bundle or using the default system certificate store.

**Comment by alanhamlett** [comment]
Just to make sure I'm prioritizing this correctly, does the bundled CA certs work on Windows with the WakaTime API?

**Comment by will7200** [comment]
On Windows, yes the request ca bundle works. Behind a cooperate proxy and/or those who have their own certificate (for whatever reason that may be) authority will not be included in the car bundle that request uses. 
I have had no issues with this at home, but work is a different story.

**Comment by alanhamlett** [comment]
Implemented and released in v10.8.0 today. To use a custom ca cert bundle file, use either argument `--ssl-certs-file /path/to/cafile.pem` or `~/.wakatime.cfg` config option:

`ssl_certs_file = /path/to/cafile.pem`

If `ssl_disable_verify = true` then this custom certfile arg/option has no effect.
