### ISSUE TITLE
Error: 'SSLError': 'HTTPSConnectionPool...

### ISSUE THREAD

**Issue by josedh** [wakatime/wakatime#165]
Hello everyone. Having an issue with vim-wakatime/7.1.3 on vim 8.1.1 on a RHEL6.5 machine (4.5.0-1.el6.elrepo.x86_64)
Its been failing for the last several weeks with this error:
```{'SSLError': 'HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(\"Can\\'t connect to HTTPS URL because the SSL module is not available.\"))', 'traceback': 'Traceback (most recent call last):\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/urllib3/connectionpool.py\", line 589, in urlopen\\n    conn = self._get_conn(timeout=pool_timeout)\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/urllib3/connectionpool.py\", line 251, in _get_conn\\n    return conn or self._new_conn()\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/urllib3/connectionpool.py\", line 827, in _new_conn\\n    raise SSLError(\"Can\\'t connect to HTTPS URL because the SSL \"\\nurllib3.exceptions.SSLError: Can\\'t connect to HTTPS URL because the SSL module is not available.\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/requests/adapters.py\", line 440, in send\\n    timeout=timeout\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/urllib3/connectionpool.py\", line 639, in urlopen\\n    _stacktrace=sys.exc_info()[2])\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/urllib3/util/retry.py\", line 388, in increment\\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(\"Can\\'t connect to HTTPS URL because the SSL module is not available.\"))\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/api.py\", line 107, in send_heartbeats\\n    verify=not args.nosslverify)\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/requests/sessions.py\", line 555, in post\\n    return self.request(\\'POST\\', url, data=data, json=json, **kwargs)\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/requests/sessions.py\", line 508, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/requests/sessions.py\", line 618, in send\\n    r = adapter.send(request, **kwargs)\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/requests/adapters.py\", line 506, in send\\n    raise SSLError(e, request=request)\\nwakatime.packages.requests.exceptions.SSLError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(\"Can\\'t connect to HTTPS URL because the SSL module is not available.\"))\\n'}```

I have looked through similiar issues reported in the past and have tried setting:
`165.227.31.73 api.wakatime.com` in my hosts files, to no avail.
Both: `165.227.31.73` and `68.183.248.166` can be pinged from my machine.
I'm starting to think it might be, like the error says, an issue with Python3 (it 'should' be using python2.6)

Any help would be appreciated.

**Comment by josedh** [comment]
Opened under the wrong repository, sorry.

**Comment by sandcore-dev** [comment]
I've actually got something similar on Debian 9.12. According to the wakatime website, no data was received since Feb 5 00:02 CET. I'm getting the impression this was caused by a change introduced in 13.0.4. I'm posting this here because I get the same error with Atom and PhpStorm:

```
{
   "plugin" : "atom-wakatime/7.2.0",
   "caller" : "[REDACTED]/.atom/packages/wakatime/lib/wakatime-master/wakatime/api.py",
   "level" : "ERROR",
   "lineno" : 225,
   "message" : "{'SSLError': \"HTTPSConnectionPool(host='api.wakatime.com', port=443): Max retries exceeded with url: /api/v1/users/current/summaries?start=today&end=today (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)'),))\", 'traceback': 'Traceback (most recent call last):\\n  File \"[REDACTED]/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 601, in urlopen\\n    chunked=chunked)\\n  File \"[REDACTED]/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 346, in _make_request\\n    self._validate_conn(conn)\\n  File \"[REDACTED]/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 850, in _validate_conn\\n    conn.connect()\\n  File \"[REDACTED]/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/urllib3/connection.py\", line 326, in connect\\n    ssl_context=context)\\n  File \"[REDACTED]/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/urllib3/util/ssl_.py\", line 329, in ssl_wrap_socket\\n    return context.wrap_socket(sock, server_hostname=server_hostname)\\n  File \"/usr/lib/python3.5/ssl.py\", line 385, in wrap_socket\\n    _context=self)\\n  File \"/usr/lib/python3.5/ssl.py\", line 760, in __init__\\n    self.do_handshake()\\n  File \"/usr/lib/python3.5/ssl.py\", line 996, in do_handshake\\n    self._sslobj.do_handshake()\\n  File \"/usr/lib/python3.5/ssl.py\", line 641, in do_handshake\\n    self._sslobj.do_handshake()\\nssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"[REDACTED]/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/adapters.py\", line 440, in send\\n    timeout=timeout\\n  File \"[REDACTED]/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 639, in urlopen\\n    _stacktrace=sys.exc_info()[2])\\n  File \"[REDACTED]/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/urllib3/util/retry.py\", line 388, in increment\\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/summaries?start=today&end=today (Caused by SSLError(SSLError(1, \\'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)\\'),))\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"[REDACTED]/.atom/packages/wakatime/lib/wakatime-master/wakatime/api.py\", line 214, in get_time_today\\n    verify=_get_verify(args))\\n  File \"[REDACTED]/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/sessions.py\", line 521, in get\\n    return self.request(\\'GET\\', url, **kwargs)\\n  File \"[REDACTED]/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/sessions.py\", line 508, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \"[REDACTED]/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/sessions.py\", line 618, in send\\n    r = adapter.send(request, **kwargs)\\n  File \"[REDACTED]/.atom/packages/wakatime/lib/wakatime-master/wakatime/packages/requests/adapters.py\", line 506, in send\\n    raise SSLError(e, request=request)\\nwakatime.packages.requests.exceptions.SSLError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/summaries?start=today&end=today (Caused by SSLError(SSLError(1, \\'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)\\'),))\\n'}",
   "now" : "2020/02/23 02:20:55 +0100",
   "time" : 1582420855.27451,
   "file" : null,
   "version" : "13.0.7"
}
```

Any suggestions on how I can resolve this?

**Comment by alanhamlett** [comment]
We've just released a new version of both Atom and PhpStorm today that should fix this.

**Comment by sandcore-dev** [comment]
I can confirm Atom is fixed now, but the PhpStorm plugin now puts a binary in the .wakatime directory and neither the SQLite database nor the log file get any new entries.

**Comment by sandcore-dev** [comment]
PhpStorm plugin 11.0 fixed it as far as I can see.

Atom plugin 9.0 works too, though it seems to hang on 'downloading wakatime-cli' in debug mode, but I am not using Atom anymore, so it's a lower priority for me. I will probably look into it though and post an issue in the appropriate repo.
