### ISSUE TITLE
"Best day" is reported with twice the real amount

### ISSUE THREAD

**Issue by kLabz** [wakatime/wakatime#166]
I just gave a look back at 2018 (thanks for the report btw!), and was really surprised to see that:
> In 2018, your best day was Sep 24 2018 with 20 hrs 5 mins.

A few years ago, I probably wouldn't notice anything there since I did do this kind of days during game jams (the date wouldn't align to a ludum dare, though), however bad it was for productivity. But now it's unthinkable that I spend so much time coding in a single day.

Clicking the link, I got the real numbers: 
> 10 hrs 2 mins on Mon Sep 24th 2018

Which is half what is on the report.

**Comment by alanhamlett** [comment]
This is due to your personal dashboard timeout preference being different from the default 15 minutes:

https://wakatime.com/faq#timeout

**Comment by kLabz** [comment]
No it's not, my timeout is 15 minutes. And I don't see why that would make the 2018 stats have twice the amount seen in the dashboard for this particular date.

**Comment by alanhamlett** [comment]
Oh sorry, I should have said probably. Will look into this and let you know here when it's fixed.

**Comment by alanhamlett** [comment]
This was indeed a bug causing coding activity to be reported twice in the report. It was fixed last week, but your cached 2018 report still contained the bug. I've recached it now, so it should be correct.

**Comment by kLabz** [comment]
Great, thanks :)

**Comment by alanhamlett** [comment]
I'll run a job tomorrow to check all users cached stats and re-cache if best day is wrong. Until then, anyone coming across this issue just comment or email support@ or toggle your timezone setting to recache your stats.

**Comment by alanhamlett** [comment]
About 12% of users stats had incorrectly cached best day. They're all invalidated now, and your [2018 Report](https://wakatime.com/a-look-back-at-2018) will either say `updating` or have the correct best day.
