### ISSUE TITLE
Need IP ranges to allow for corporate firewall and git integration

### ISSUE THREAD

**Issue by rizzdev** [wakatime/wakatime#167]
Wakatime gives a nice option for self hosted Git Lab, however in most cases a self hosted environment is normally behind a firewall (in our case it is). We need to know which IP ranges to let through so we can integrate.

![image](https://user-images.githubusercontent.com/11708861/54388968-64563500-4675-11e9-893c-4845ffd01868.png)

**Comment by alanhamlett** [comment]
We have an API endpoint available for that:

From the docs at https://wakatime.com/developers/#meta:

> ## Meta
> https://wakatime.com/api/v1/meta
> 
> ### Description
> 
> Information about WakaTime, such as a list of public ip addresses used by WakaTime servers

**Comment by alanhamlett** [comment]
Also, #96 is an alternate solution for the future.

**Comment by rizzdev** [comment]
@alanhamlett Thank you! You should put a link to this directly on the page. I spent a ton of hours googling for your ip ranges!

**Comment by alanhamlett** [comment]
Added a link to the IPs from GitLab self-hosted setup flow on the website.
