### ISSUE TITLE
Does not Work with Notepad++ V7.6.3 (64-Bit) 

### ISSUE THREAD

**Issue by tb-mtg** [wakatime/wakatime#168]
Followed the instructions from https://wakatime.com/notepad++  but it does not work.

The Notepad++ version installed is V7.6.3 (64-Bit) installed on Windows 10.

Others are also having problems as shown in issue below, but with have had no help so far:
https://github.com/wakatime/notepadpp-wakatime/issues/32

**Comment by DanRowe1** [comment]
Same here. 
![image](https://user-images.githubusercontent.com/47305015/55297070-23d61580-53f0-11e9-9601-9c821e4ff7cd.png)

**Comment by gandarez** [comment]
Released v4.1.0 https://github.com/wakatime/notepadpp-wakatime/releases/tag/4.1.0

**Comment by alanhamlett** [comment]
Notepad++ x64bit support was added with #33.

**Comment by tb-mtg** [comment]
Thanks
