### ISSUE TITLE
Some public profiles use their API key as an identifier?

### ISSUE THREAD

**Issue by sisou** [wakatime/wakatime#17]
Taken from the Leaderboard (https://wakatime.com/leaders):
Examle: https://wakatime.com/@8415cccb-18af-413c-be3c-4e3b53d8c526

**Comment by alanhamlett** [comment]
Yes, because they haven't chosen a username yet.

**Comment by sisou** [comment]
It means other people could impersonate them though and submit data to their profile?

**Comment by alanhamlett** [comment]
Oh, no that is not their api key. That's their public user id.
