### ISSUE TITLE
Feature Request: device stats

### ISSUE THREAD

**Issue by LorenzoLeonardini** [wakatime/wakatime#179]
Hi!
I've been using Wakatime for a while and I love how it shows you the stats about which editor and which OS you've been using.
When people work on more than one machine, though, (that's the meaning on the OS stats, isn't it?) it would be cool to have time stats about the device you've been coding on. I don't think that would be a huge problem to implement, since the data is all there.
Thanks

**Comment by alanhamlett** [comment]
That's currently only available through the api from the `machines` attribute on stats response:
https://wakatime.com/developers/#stats
