### ISSUE TITLE
Old website URLs should be redirecting

### ISSUE THREAD

**Issue by impressivewebs** [wakatime/wakatime#18]
These old links are broken:

https://www.wakati.me/
http://www.wakati.me/
https://wakati.me

I'm assuming those should all redirect to:

https://wakatime.com/

This one redirects fine:

http://wakati.me (no https)

(sorry if this is the wrong place for this issue)

**Comment by alanhamlett** [comment]
Are there links to wakati.me still?

**Comment by impressivewebs** [comment]
I'm not sure. I had one in one of my newsletter issues, which I've now changed. But the MailChimp archived version will still have the old link. Not a big deal as few people will open those old issues anyhow, but I have no idea how many other links are out there, you'd have to do a search I suppose.

**Comment by impressivewebs** [comment]
Quick search brought up this page:

http://www.reddit.com/domain/wakati.me/

So yeah, there are links.

**Comment by alanhamlett** [comment]
Ok, I'll have to setup a server to forward to the new domain. Thanks!
