### ISSUE TITLE
Heartbeat response has only id

### ISSUE THREAD

**Issue by Hermesiss** [wakatime/wakatime#181]
Found in https://github.com/vladfaust/unity-wakatime

[Expectation](https://wakatime.com/developers#heartbeats):
```json
{
  "data": {
    "id": "xxx",
    "entity": "yyy",
    "type": "zzz",
    "time": 123.456,
  }
}
```
Reality:
`{"data":{"id":"xxx"}}`

**Comment by alanhamlett** [comment]
Fixed!
