### ISSUE TITLE
Exclude project on windows 

### ISSUE THREAD

**Issue by abdulmalekDery** [wakatime/wakatime#192]
I have read the docs and edited my .wakatime.cfg to be like this

[settings]
api_key = XXXXXXX-XXXX-XXXX-XXXX-XXXXXX
exclude =C:\Users\informatic\JungleBird.Android
 
but waka time is still tracking that project. how to prevent waka from that?

**Comment by alanhamlett** [comment]
Try this instead:

```
[settings]
api_key = XXXXXXX-XXXX-XXXX-XXXX-XXXXXX
exclude = [\\/]Users[\\/]informatic[\\/]JungleBird.Android
```

Since it's using POSIX regular expressions it needs backslashes escaped, and better to match both back and forward slash because both are accepted by WakaTime on Windows.
