### ISSUE TITLE
API Question 

### ISSUE THREAD

**Issue by wagnernegrao** [wakatime/wakatime#197]
Hi,
I do software engineering research, I wonder if it is possible to extract data from multiple users through the API, similar to GitHub. I read the documentation, but it was not clear to me.

**Comment by alanhamlett** [comment]
You can read user `last_7_days` stats if they've made it public in their profile settings, and if you have their user id:
https://wakatime.com/developers/#stats

**Comment by wagnernegrao** [comment]
Thanks,

Is it possible to get the user ID through the API?

**Comment by alanhamlett** [comment]
Yes, through the leaderboard endpoint, which also contains `last_7_days` stats for users in it's response:
https://wakatime.com/developers/#leaders

**Comment by wagnernegrao** [comment]
Thanks,

I created an application as requested in the documentation, but when accessing via terminal, I get a link, but this link presents

```
Error 400
Invalid Redirect_uri: Invalid for this client.
```

Sorry for so many questions =)

**Comment by alanhamlett** [comment]
Apps are only needed when you want to use OAuth so users can grant you permission(s) on their account. Those two endpoints don't require authentication.

**Comment by wagnernegrao** [comment]
Do I have a request limit?

I got the user id in leaders but when using the user id in stats I get ```Response [404]```

**Comment by alanhamlett** [comment]
A `404` code means `Not Found`, so something is wrong with the URL path.

**Comment by wagnernegrao** [comment]
The truth was wrong, I'm using this URL `https: //wakatime.com/api/v1/users/:user/stats/:last_7_days?api_key = ****` to try to get user data from his ID.

**Comment by alanhamlett** [comment]
Here's an example using my user id:

https://wakatime.com/api/v1/users/66b6796d-eb84-4bb9-b9d2-8dc882f4c6ac/stats/last_7_days

The `api_key` isn't needed for this endpoint, since your account won't have any permissions to see more data for my user id.

**Comment by wagnernegrao** [comment]
Got it thanks, if I wanted to verify the data as commit will I need more permission?

**Comment by alanhamlett** [comment]
Verify the data as commit, you mean associate WakaTime durations with GitHub commits? Yes, that's only available if each user grants you permission to view their coding activity with OAuth, so not possible for research purposes.

**Comment by wagnernegrao** [comment]
Yes, I wanted to associate the commit data with GitHub data and later with Travis and from there find some relationship with continuous integration, currently working with CI. But I believe that with the current data that the API returns I can already work, but not with CI.

Thank you so much for taking my questions were of great help.
