### ISSUE TITLE
Logging wrong name of the project

### ISSUE THREAD

**Issue by gandarez** [wakatime/wakatime#20]
Hi all!
I've been using Wakatime plugin for Visual Studio 2013 for 2 weeks. Found a silly problem related to pyton scripts. The project name that I'm using is "PagedList" which is under branch name "localization". Debugging visualstudio-wakatime plugin I could figure out that the problem is not there as the screenshot below.
![image](https://cloud.githubusercontent.com/assets/782854/7633679/11073794-fa2c-11e4-826b-065c6e9c27b0.png)
arguments = **"C:\Users\cgandarez\wakatime-master\wakatime\cli.py" --key="###" --file="c:\git\gandarez\pagedlist\localization\src\pagedlist.mvc\pagedlistrenderoptions.cs" --plugin="visualstudio/12.0 visualstudio-wakatime/4.0.2" --project="PagedList"**

Taking a look at debugging log it seems to guide us to the error. The project name is set to "localization" instead of "PagedList":
```{"now": "2015/05/14 11:10:50 E. South America Standard Time", "version": "4.0.8", "plugin": "visualstudio/12.0 visualstudio-wakatime/4.0.2", "time": 1431612650.260504, "file": "c:\\git\\gandarez\\pagedlist\\localization\\src\\pagedlist.mvc\\gotoformrenderoptions.cs", "level": "DEBUG", "message": {"project": "localization", "language": "C#", "time": 1431612650.260504, "lines": 60, "dependencies": ["PagedList.Mvc", "PagedList"], "branch": "localization", "file": "c:\\git\\gandarez\\pagedlist\\localization\\src\\pagedlist.mvc\\gotoformrenderoptions.cs"}}```

```python
def _project_base(self):
        if self.configFile:
            return os.path.dirname(os.path.dirname(self.configFile))
        return None
```
It's getting as project base "localization" folder which seems not to be wrong. The main problem is when base.main() is executed. It seems not respecting "--project" parameter informed.

**Comment by gandarez** [comment]
After making effort to identify this issue I assume there's a silly definition about "--project" parameter. If those arguments have project name the base.py script has to respect it. I won't take priority over arguments as commented in the code.

"optional project name; auto-discovered project takes priority"

**Comment by alanhamlett** [comment]
The reason the auto-detected project takes priority is because some editors use strange default project names which the user can't control. I'll add a new option `--alternate-project` so `--project` will always be used.

**Comment by alanhamlett** [comment]
Re-installing the plugin in Visual Studio will fix this issue for you.

**Comment by gandarez** [comment]
@alanhamlett I deleted the folder which contains python scripts to force redownload. You rock! It's been working!
