### ISSUE TITLE
UnicodeDecodeError on Atom

### ISSUE THREAD

**Issue by jerry871002** [wakatime/wakatime#200]
I am using 

- macOS 10.14.6
- Atom 1.42.0 
- Wakatime 7.1.2

I got the following error while trying to edit a file on Atom

![image](https://user-images.githubusercontent.com/29112212/71050944-9b67f280-2181-11ea-9ea0-3c6dd9594928.png)

The Dev Console displays this warning

```
[WakaTime] [WARN] [wakatime.coffee:563] Error: Command failed: python3 /Users/Jerry_Yang/.atom/packages/wakatime/lib/wakatime-master/wakatime/cli.py --file /Users/Jerry_Yang/Desktop/test.cpp --plugin atom-wakatime/7.1.2 --lineno 1 --config /Users/Jerry_Yang/.wakatime.cfg --alternate-project Desktop
Failed to import the site module
Traceback (most recent call last):
  File "/Users/Jerry_Yang/anaconda/lib/python3.6/site.py", line 550, in <module>
    main()
  File "/Users/Jerry_Yang/anaconda/lib/python3.6/site.py", line 532, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/Jerry_Yang/anaconda/lib/python3.6/site.py", line 320, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/Jerry_Yang/anaconda/lib/python3.6/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/Jerry_Yang/anaconda/lib/python3.6/site.py", line 163, in addpackage
    for n, line in enumerate(f):
  File "/Users/Jerry_Yang/anaconda/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 79: ordinal not in range(128)
```

How do I fix this?

**Comment by jerry871002** [comment]
I have tried to reinstall wakatime package on atom and also atom itself, both didn't work.
Wakatime on Xcode and PyCharm on my computer are still working, so it might probably be a problem only on Atom?

**Comment by alanhamlett** [comment]
WakaTime isn't tested with Anaconda Python on Mac, can you try temporarily uninstalling Anaconda?

**Comment by alanhamlett** [comment]
The error message `Failed to import the site module` means Anaconda Python is corrupted/broken.

**Comment by jerry871002** [comment]
> WakaTime isn't tested with Anaconda Python on Mac, can you try temporarily uninstalling Anaconda?

It works after I removed anaconda from `PATH`! So it seems to be a problem with Anaconda.

But I am wondering why wakatime works properly on Xcode and PyCharm with Anaconda?

**Comment by alanhamlett** [comment]
WakaTime for Xcode is hard-coded to use `/usr/bin/python`:
https://github.com/wakatime/xcode-wakatime/blob/fa6421ed60e009407e3b353c280ba3fecd89a626/WakaTime/WakaTime.m#L224

WakaTime for PyCharm checks your PATH first then multiple common locations for Python:
https://github.com/wakatime/jetbrains-wakatime/blob/614ec371e67c221e9dd44e9a2ee4737aa94927ef/src/com/wakatime/intellij/plugin/Dependencies.java#L72

Atom is similar to PyCharm, but implemented differently:
https://github.com/wakatime/atom-wakatime/blob/cb1b51c60d5a8e90a0aa13d43cd4a9c64674438f/lib/wakatime.coffee#L278

That implementation difference is why Atom used Anaconda but PyCharm and Xcode didn't.
