### ISSUE TITLE
Contribute to wakatime

### ISSUE THREAD

**Issue by LoukasPap** [wakatime/wakatime#205]
Hello, i am a university student and i have a course related with Open Software Systems. An assignment we have, is to contribute to an OSS by solving an issue or two of it. Will you accept my pull request if I manage to close an open issue? Thank you.

**Comment by alanhamlett** [comment]
[As seen here](https://github.com/wakatime/wakatime/pulls?q=is%3Apr+is%3Aclosed), yes we merge PRs. Also please only use GitHub issues to report bugs, not ask general questions.
