### ISSUE TITLE
How to execute the cli locally for contributing to development

### ISSUE THREAD

**Issue by LoukasPap** [wakatime/wakatime#206]
Hello, i am trying to build wakatime and run it locally, so that i can test my changes, but i don't know how. I've tried some things but nothing happens. Please give me some instructions in detail on how to do it! Thank you.

**Comment by DinosXa** [comment]
i have the same issue . please help

**Comment by alanhamlett** [comment]
The best way is using the [standalone branch install instructions](https://github.com/wakatime/wakatime/tree/standalone#contributing).

After `pipenv install`, run `pipenv run python ./wakatime/wakatime-cli.py` execute the cli.

**Comment by alanhamlett** [comment]
Also, you should know we're deprecating this repo in favor of https://github.com/wakatime/wakatime-cli, so no more updates will be made to this repo.
