### ISSUE TITLE
Unknown OS: Showing Unknown OS instead of Mac OS

### ISSUE THREAD

**Issue by VictorAlagwu** [wakatime/wakatime#209]
I notice that for a while(The first occurrence was in the March 2nd report), instead of showing Mac as the operating system in the weekly report, it shows Unknown OS instead, I notice the issue occur regardless of the IDE/Editor being used

March 2nd
![March 2nd](https://user-images.githubusercontent.com/15857679/79737756-b2674e80-82f3-11ea-9764-e71b060ed490.png)

March 16th 
![March 16th](https://user-images.githubusercontent.com/15857679/79737765-b72c0280-82f3-11ea-81b0-ee99872563c8.png)

March 23rd
![March 23rd](https://user-images.githubusercontent.com/15857679/79737777-bc894d00-82f3-11ea-985c-036a21ff3670.png)

April 20th
![April 20th](https://user-images.githubusercontent.com/15857679/79737789-c0b56a80-82f3-11ea-9629-01c337291203.png)

**Comment by alanhamlett** [comment]
Thanks for the report, we were only detecting OS based on `darwin`. It's fixed now by checking for `macos`.
