### ISSUE TITLE
Feature Request: File extension associations 

### ISSUE THREAD

**Issue by nixin72** [wakatime/wakatime#214]
A lot of the time file extensions can overlap. For example, Puppet and Racket's Pollen library both use the `.pp` extension, so when I'm using Pollen it ends up showing up as Puppet, when in reality I'd like it to show Racket (or, ideally Pollen). It would also allow languages to be included as a "best fit", for example Wakatime doesn't have support for Emacs org-mode (the language shows up as "other"), however Org-mode is quite close to Markdown, so maybe when doing org-mode work it can be associated to show up as Markdown. 

On that note, being able to associate a given extension with a string as any language name would be very cool and see it show up as that language, but I'd imagine that would be a whole other feature. For example when I run `wakatime --entity index.html.pp --language "pollen"` it would show up as pollen, and when I added to my `.wakatime.cfg` 
```
[associations]
pollen = *.pp
```
Then all `.pp` files would default to Pollen instead of Puppet.

**Comment by adreasnow** [comment]
You can accomplish this in the wakatime account settings through 'Settings --> Custom Rules', to set different languages

**Comment by nixin72** [comment]
Oh, thank you! I never noticed this before!
