### ISSUE TITLE
problem:wakatime Failed to establish a new connnection

### ISSUE THREAD

**Issue by hanm2019** [wakatime/wakatime#215]
I was using wakatime in ubuntu 18.04, i use pip install the wakatime firstly, and use wakatime in zsh and emacs, but in the last 3 day, i found my dashboard working time is 0, so, i make the wakatime.cfg debug = true, and the log is blow:
```
{"now": "2020/05/29 16:58:55 +0000", "version": "13.0.7", "plugin": "emacs-wakatime/1.0.2", "time": 1590742735.2, "caller": "/usr/local/lib/python2.7/dist-packages/wakatime/api.py", "lineno": 124, "is_write": true, "file": "/home/hanm/.wakatime.cfg", "level": "WARNING", "message": "{'ProxyError': u\"HTTPSConnectionPool(host='api.wakatime.com', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5486656c10>: Failed to establish a new connection: [Errno 111] Connection refused',)))\", 'traceback': 'Traceback (most recent call last):\\n  File \"/usr/local/lib/python2.7/dist-packages/wakatime/api.py\", line 110, in send_heartbeats\\n    verify=_get_verify(args))\\n  File \"/usr/local/lib/python2.7/dist-packages/wakatime/packages/requests/sessions.py\", line 555, in post\\n    return self.request(\\'POST\\', url, data=data, json=json, **kwargs)\\n  File \"/usr/local/lib/python2.7/dist-packages/wakatime/packages/requests/sessions.py\", line 508, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \"/usr/local/lib/python2.7/dist-packages/wakatime/packages/requests/sessions.py\", line 618, in send\\n    r = adapter.send(request, **kwargs)\\n  File \"/usr/local/lib/python2.7/dist-packages/wakatime/packages/requests/adapters.py\", line 502, in send\\n    raise ProxyError(e, request=request)\\nProxyError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by ProxyError(\\'Cannot connect to proxy.\\', NewConnectionError(\\'<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5486656c10>: Failed to establish a new connection: [Errno 111] Connection refused\\',)))\\n'}"}
```

my wakatime.cfg is :
```
[settings]
debug = true 
api_key = my-secret-key
hide_file_names = false
hide_project_names = false
hide_branch_names =
exclude =
    ^COMMIT_EDITMSG$
    ^TAG_EDITMSG$
    ^/var/(?!www/).*
    ^/etc/
include =
    .*
include_only_with_project_file = false
status_bar_icon = true
status_bar_coding_activity = true
offline = true
proxy = https://user:pass@localhost:8080
no_ssl_verify = false
ssl_certs_file =
timeout = 30
hostname = hanm 
[projectmap]
projects/foo = new project name
^/home/user/projects/bar(\d+)/ = project{0}
[git]
disable_submodules = false
```

the api-key in configuration in init.el of emacs and in the .wakatime.cfg and i'm sure the api-key is correct.

**Comment by hanm2019** [comment]
more log file which i think maybe helpful.
{"now": "2020/05/29 17:12:14 +0000", "version": "13.0.7", "plugin": "wakatime-zsh-plugin/0.2.1", "time": 1590743534.817251, "caller": "/usr/local/lib/python2.7/dist-packages/wakatime/api.py", "lineno": 56, "is_write": true, "file": "python", "level": "DEBUG", "message": "Sending heartbeats to api at https://api.wakatime.com/api/v1/users/current/heartbeats.bulk"}
{"now": "2020/05/29 17:12:14 +0000", "version": "13.0.7", "plugin": "wakatime-zsh-plugin/0.2.1", "time": 1590743534.817251, "caller": "/usr/local/lib/python2.7/dist-packages/wakatime/api.py", "lineno": 62, "is_write": true, "file": "python", "level": "DEBUG", "message": "[{'is_write': True, 'entity': u'python', 'dependencies': [], 'category': None, 'language': None, 'lines': None, 'project': u'Terminal', 'cursorpos': None, 'lineno': None, 'branch': None, 'time': 1590743534.817251, 'type': 'app', 'user_agent': u'wakatime/13.0.7 (Linux-5.3.0-53-generic-x86_64-with-Ubuntu-18.04-bionic) Python2.7.17.final.0 wakatime-zsh-plugin/0.2.1'}]"}
{"now": "2020/05/29 17:12:14 +0000", "version": "13.0.7", "plugin": "wakatime-zsh-plugin/0.2.1", "time": 1590743534.817251, "caller": "/usr/local/lib/python2.7/dist-packages/wakatime/api.py", "lineno": 124, "is_write": true, "file": "python", "level": "WARNING", "message": "{'ProxyError': u\"HTTPSConnectionPool(host='api.wakatime.com', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7230822bd0>: Failed to establish a new connection: [Errno 111] Connection refused',)))\", 'traceback': 'Traceback (most recent call last):\\n  File \"/usr/local/lib/python2.7/dist-packages/wakatime/api.py\", line 110, in send_heartbeats\\n    verify=_get_verify(args))\\n  File \"/usr/local/lib/python2.7/dist-packages/wakatime/packages/requests/sessions.py\", line 555, in post\\n    return self.request(\\'POST\\', url, data=data, json=json, **kwargs)\\n  File \"/usr/local/lib/python2.7/dist-packages/wakatime/packages/requests/sessions.py\", line 508, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \"/usr/local/lib/python2.7/dist-packages/wakatime/packages/requests/sessions.py\", line 618, in send\\n    r = adapter.send(request, **kwargs)\\n  File \"/usr/local/lib/python2.7/dist-packages/wakatime/packages/requests/adapters.py\", line 502, in send\\n    raise ProxyError(e, request=request)\\nProxyError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by ProxyError(\\'Cannot connect to proxy.\\', NewConnectionError(\\'<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7230822bd0>: Failed to establish a new connection: [Errno 111] Connection refused\\',)))\\n'}"}

**Comment by gandarez** [comment]
It's somehow trying to connect through a proxy which is defined in your `~/.wakatime.cfg`. Could you please remove all unncessary configs from the file and try again? I believe you only need `api_key`, `debug`, `status_bar_icon` and `status_bar_coding_activity`.

**Comment by hanm2019** [comment]
it work, thank you. 
I think the README  about wakatime.cfg should make a illustrate that this template should not copy whole of it when you are using in a normal way
