### ISSUE TITLE
My VS Code lags when I enable wakatime 

### ISSUE THREAD

**Issue by AF1QUE** [wakatime/wakatime#223]
Hello, I really like your addon - WakaTime but it lags my coding experience. When I start typing for a while my text appears a bit late and lags a lot. I have tested the visual studio code by disabling your addon and it worked fine it only lags when I use WakaTime. 

FYI, my specs are -  
- Intel Core i5 6th gen
- 8gb ddr3 ram 
- Windows 10

**Comment by thejoycekung** [comment]
This issue sounds like it's related to [vscode-wakatime](https://github.com/wakatime/vscode-wakatime), more than the CLI.

**Comment by AF1QUE** [comment]
@thejoycekung I was unaware of that repo. I will post there. Thanks.
