### ISSUE TITLE
API Endpoint to get total time spent on project

### ISSUE THREAD

**Issue by TECHNOFAB11** [wakatime/wakatime#226]
It would be great to have an api endpoint (or a param added to the projects endpoint) that would allow the user to add the time directly into the application (for example on an about site or so) or in the CI/CD (for example in a changelog, etc.). 
This already is possible with a really hacky solution by using the badge. But it would be better to just have it in the API and officially supported than having to scrape the badge :)

**Comment by alanhamlett** [comment]
We do have one, but it's not documented. Replace `proj` with the real project name:
https://wakatime.com/api/v1/users/current/all_time_since_today?project=proj

For this endpoint you'll need a retry with ~5 second timeout while it's calculating the time in the background. While it's calculating, it returns a `202` response with `is_up_to_date: false`. When the total time's ready, it returns a `200` response with the total time for your project. For ex:

```JSON
{
  "data": {
    "is_up_to_date": true,
    "project": "wakatime",
    "text": "3,715 hrs 44 mins",
    "total_seconds": 13376647.007382
  }
}
```

**Comment by alanhamlett** [comment]
Added docs for this endpoint here:
https://wakatime.com/developers/#all_time_since_today

**Comment by TECHNOFAB11** [comment]
Cool, thanks a lot!
