### ISSUE TITLE
Incorrect sync of API and dashboard data

### ISSUE THREAD

**Issue by Daggy1234** [wakatime/wakatime#227]
<img src="https://daggy.is-a-virg.in/yM4KDv.png" />

The above link is my dashboard.

<img src="https://daggy.is-a-virg.in/rvdktf.png" />

the above is my API statistics.

My APIs stats have not changed for the last 2 hours despite my dashboard updating consistently.

**Comment by Daggy1234** [comment]
fyi the link I used was 

https://wakatime.com/api/v1/users/current/stats/last_7_days?api_key={my_api_key}

**Comment by alanhamlett** [comment]
The `stats` api endpoint shows time as a fixed range (`last_7_days`) from Yesterday, so it never includes Today's time until after midnight. What you need is the `summaries` endpoint, which is what your dashboard is using.
