### ISSUE TITLE
Feature Request: all_time_since_today in languages embedded json

### ISSUE THREAD

**Issue by t36campbell** [wakatime/wakatime#228]
Hello, Im a huge fan of your app and would love to use the embedded json to show the "all time since today" metric along side  the embedded charts. Im currently using (only in testing) the embedded json on my website to get the all time languages data then making another call to get the "all time since today" number. With these I can "solve for x" but as stated in your api doc, I shouldnt be using my api key on a public website. 

Updating the json data provided by the embedded chart to provide the all time data broken down by language would allow me to publish these stats on my portfolio without a risk to my account.

Heres an example of what I think the response would look like: 
```
{
    "data": {
        all_time[{
            "is_up_to_date": true,
            "digital": "199:09",
            "hours": 199,
            "minutes": 9,
            "text": "199 hrs 9 mins",
            "total_seconds": 716965.091027
        }],
        languages[{
            "color": "#16ce40",
            "digital": "71:01",
            "hours": 71,
            "minutes": 1,
            "name": "Vue.js",
            "percent": 35.66,
            "text": "71 hr 1 min",
            "total_seconds": 255669.751460
        }, {
            "color": "#f1e05a",
            "digital": "44:58",
            "hours": 44,
            "minutes": 58,
            "name": "JavaScript",
            "percent": 22.58,
            "text": "44 hr 58 min",
            "total_seconds": 161890.717554
        }, {
            "color": "#31859c",
            "digital": "29:15",
            "hours": 29,
            "minutes": 15,
            "name": "TypeScript",
            "percent": 14.69,
            "text": "29 hr 15 min",
            "total_seconds": 105322.171872
        }, ]
    }
```

Thank you for your time and consideration.

**Comment by alanhamlett** [comment]
You can use the new "All time" range for the embeddable coding activity chart with JSON format to accomplish this.

**Comment by t36campbell** [comment]
> You can use the new "All time" range for the embeddable coding activity chart with JSON format to accomplish this.

Awesome. This helps me out so much thank you
