### ISSUE TITLE
Offline time in .wakatime.db never uploaded

### ISSUE THREAD

**Issue by Yohandah** [wakatime/wakatime#229]
Hello,

I was behind a proxy for 6 months and I have a .wakatime.db of 60 000ko but now that I have access to the internet again (new activity is uploading) my IntelliJ extension isn't uploading my .wakatime.db, I tried the Atom extension and the VSCode extension as well and they don't upload it.

Is there a way to upload it manually ? Or force the upload ? 

I opened the .wakatime.db manually with a SQLite browser and I have 50000+ entries with data not appearing in my dashboard.

Thanks

**Comment by Yohandah** [comment]
Got my answer on Twitter 🙂

https://twitter.com/wakatime/status/1302994092201095169?s=21

**Comment by alanhamlett** [comment]
Pasting here for documentation:

> Yes, u can sync it manually using:
`wakatime-cli --sync-offline-activity 99999`. You're using Win or Linux/Mac? For win: `%APPDATA%\WakaTime\wakatime-cli\wakatime-cli --sync-offline-activity 99999` OR for Linux/Mac: `~/.wakatime/wakatime-cli/wakatime-cli --sync-offline-activity 99999`
