### ISSUE TITLE
Feature Request: micro plugin

### ISSUE THREAD

**Issue by muety** [wakatime/wakatime#232]
I'm using [micro](https://micro-editor.github.io/) as my primary command-line text editor and would love to have a Wakatime plugin for it. Micro offers a pretty intuitive Lua-based plugin system to extend it.

**Comment by gandarez** [comment]
@muety WakaTime micro-editor plugins has been released. You'll need first to build micro from source since our changes and additions to micro will be released soon.

https://github.com/zyedidia/micro#building-from-source
https://github.com/wakatime/micro-wakatime#installation

**Comment by muety** [comment]
Wow, that's great! Thank you so much! To be fair, I didn*t really expect this plugin to be realized, as `micro` is not that widely used to real IDEs like IntelliJ, VSCode, etc. Thanks for your efforts!

**Comment by gandarez** [comment]
Feel free to open any issue at micro-wakatime repo.
