### ISSUE TITLE
No time tracked but no errors

### ISSUE THREAD

**Issue by shardick** [wakatime/wakatime#24]
Hi,

my wakatime plugin for Visual Studio 2013 (installed on a virtual machine at work) is not tracking anything: .wakatime.log is empty and ActivityLog.xml contains no errors.

.wakatime.cfg contains the api key. 

At home, same api key, is working.

Maybe connection issue? This virtual machine is not under proxy for development purpose.

Thank you!

**Comment by alanhamlett** [comment]
At work you need a proxy to connect to the outside internet?

On Mon, Jun 1, 2015 at 1:55 AM, Francesco Bramato <notifications@github.com>
wrote:

> Hi,
>
> my wakatime plugin for Visual Studio 2013 (installed on a virtual machine
> at work) is not tracking anything: .wakatime.log is empty and
> ActivityLog.xml contains no errors.
>
> .wakatime.cfg contains the api key.
>
> At home, same api key, is working.
>
> Maybe connection issue? This virtual machine is not under proxy for
> development purpose.
>
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wakatime/wakatime/issues/24>.
>



-- 
Alan
ahamlett.com

**Comment by shardick** [comment]
No, or almost, i think. I've asked to my network admins and he told me that the development virtual macchine go out directly

**Comment by shardick** [comment]
(Ops i closed the issue!)

**Comment by shardick** [comment]
Hi Alan,
i've debugged the visual studio extension to find out why is not working on my machine.

So, GetPython() returns always null but the extension try to install every time visual studio starts: Python got installed correctly, it is present in c:\pyton34 but when it try to execute it the RunProcess.OK() is always false.

To solve i've added c:\python34 to environment variable PATH and now it works :)

**Comment by alanhamlett** [comment]
Glad you've solved it.

That's strange the plugin wasn't able to find Python at c:\python34. Was it c:\pyton34 or c:\python34? Maybe I need to add c: before each path location in [GetPython()](https://github.com/wakatime/visualstudio-wakatime/blob/64dbc1839434ffa76a42d7699549b966ddaae27b/WakaTimePackage.cs#L195).

**Comment by shardick** [comment]
Sorry, it's c:\python34 .

Why don't make configurable that path with a default? maybe i could have the Python installation in another path :)

**Comment by alanhamlett** [comment]
wakatime/visualstudio-wakatime#18 uses the Windows registry to find Python, so this should be solved now.
