### ISSUE TITLE
API wrongly includes time removed from old project using custom rules as current activity

### ISSUE THREAD

**Issue by betoma** [wakatime/wakatime#244]
Near the beginning of my time using wakatime, I had some programming activity accidentally assigned to a project called "code" before I learned how to set project names using .wakatime-project. I did that for future activity and then used a custom rule on the wakatime website to move the past activity into the new (correct) project. This worked as far as the website's display goes, and I recently deleted the old "code" project without any issues as far as how the projects are displayed on the wakatime website.

However, API calls still return the time spent on this now-deleted "code" project as though it's current activity -- including counting it when it calculates percentage of time spent per project over a timespan. The amount of time is always 41 minutes, with the percentage changing based on how much other coding activity was logged by wakatime that week. This is most readably evident in its appearance in my [updating github readme](https://github.com/betoma/betoma/commits/master/README.md) which directly calls the API to display time spent per project as a graph. However, I have checked that this data is returned directly from the wakatime API call rather than being some bug in the readme update action. 

Why is this old activity continually returned as new activity by the API? I hoped deleting the project would get rid of the issue, but it does not appear to have done so.

**Comment by LuchaoQi** [comment]
Yeah, similar problem. Is there any way to fully reset the custom rules that were applied to the data previously?

**Comment by alanhamlett** [comment]
Try manually running the Action to update your profile readme, does that update it? [The action](https://github.com/anmol098/waka-readme-stats) uses the [WakaTime stats api](https://wakatime.com/developers/#stats), which is heavily cached. Normally cached stats update once per day, or as needed lazily in the background as needed. The stats response always sends back a boolean `is_up_to_date` showing whether the returned data is fresh or stale.

**Comment by betoma** [comment]
I've manually run the action and in addition I've also queried the API directly myself and seen that it was indeed returning this old activity when I asked for my activity over the last week. This activity is from months and months ago, so if I hadn't used a custom rule it wouldn't be turning up in my activity over the last week at all.

**Comment by alanhamlett** [comment]
It's fixed now on our end!
