### ISSUE TITLE
WakaTime Projects not showing the branches name anymore

### ISSUE THREAD

**Issue by alexanderluiscampino** [wakatime/wakatime#248]
Hi,

Until very recently the WakaTime project section I could see the time spent on each branch, which was extremely useful since it had the ticket name. Now it just shows unknown. Is this something that changed on WakaTime or is on my VisualCode/Git ?

![image](https://user-images.githubusercontent.com/32500355/102806971-ac3ddc00-4372-11eb-9289-cc57defa59b4.png)

**Comment by alanhamlett** [comment]
Oops, this was a display-only bug introduced when we rolled out [External Durations](https://wakatime.com/developers/#external_durations) over the weekend. It's fixed now, thanks!
