### ISSUE TITLE
Add spend a time to commit messages

### ISSUE THREAD

**Issue by bimawa** [wakatime/wakatime#25]
I working on a few projects where we use Assembla.com, redmine, youtrack and etc. all of this platforms support parsing commit messages for link commits with a task and spended time. It will be very cool if wakatime plugin for AppCode (and similar IDE by JB) add spend timer to commit message, for each platform separately.

**Comment by magnucki** [comment]
This would be pretty awesome!

**Comment by alanhamlett** [comment]
Added support for time spent per commit with the [GitHub integration](https://wakatime.com/integrations) (https://wakatime.com/features).

**Comment by toptalo** [comment]
Hello! How to add time to commit message?
Is it works only with GitHub? How about GitLab?
