### ISSUE TITLE
Typo on the vim page on website

### ISSUE THREAD

**Issue by jrnewton** [wakatime/wakatime#251]
I couldn't find a repo for the website so I hope this is an okay place to report the problem.

URL: https://wakatime.com/vim

In the section "Installing with Vim-Plug" , the example config says to install 'tpope/vim-fireplace'.  Clearly should be 'wakatime/vim-wakatime' :smiley:  The README in vim-wakatime does not have this mistake.

**Comment by profiluefter** [comment]
Seems like this was fixed

**Comment by alanhamlett** [comment]
Yep, it was fixed a while back.
