### ISSUE TITLE
How do I write custom rule to ignore certain languages/projects?

### ISSUE THREAD

**Issue by weeebdev** [wakatime/wakatime#256]
I want to write a custom rule to delete or ignore the whole language from my stats:
E.g. my Chrome browser displays as Browserlist in the Languages (I wrote it like that in order to differentiate my Browser time from Others language). Of course, I spend a lot of time in the browser, so in the Languages field my browser takes 30-40% of space making other languages very small in the chart. I would like to ignore it or delete completely without removing the Project.

**Comment by alanhamlett** [comment]
That's done with your client-side config file by excluding folders/files:
https://wakatime.com/faq#exclude-paths
