### ISSUE TITLE
API rate limit

### ISSUE THREAD

**Issue by muety** [wakatime/wakatime#261]
Importing many batches of heartbeats from WakaTime into Wakapi brouch up an issue (https://github.com/muety/wakapi/issues/152) that is most likely caused by WakaTime not fulfilling some of those requests. I still need to investigate what the exact response status code and body looks like in those cases, but I would assume a `500` or `429` error.

I'd like to know: does WakaTime's API enforce some kind of rate limiting or is there a known issues related to many incoming requests from the same IP within a short time span?

**Comment by muety** [comment]
Thanks for the quick reply. I'll adapt the import process accordingly.

**Comment by alanhamlett** [comment]
It's actually 10 requests per second on average over the last 5 minutes. I'll update the docs.
