### ISSUE TITLE
Microsoft Sql Server Management Studio plugin

### ISSUE THREAD

**Issue by diegomesata** [wakatime/wakatime#27]
Hello, it will be nice a Microsoft Sql Server Management Studio, I spend many development time there.

Thank you

**Comment by alanhamlett** [comment]
This page says extensions are not supported, so I'll have to find unofficial documentation on creating a plugin:
> SQL Server Management Studio is built upon the Visual Studio Isolated Shell, which inherently supports extensibility (add-ins/plug-ins). It is possible to tap into the Visual Studio extensibility services to surface custom capabilities within SQL Server Management Studio; however, such extensibility is not supported.
>
> There are some users and third parties that have developed extensions to SQL Server Management Studio. While we do not discourage this, keep in mind that such extensibility is not supported, so there may be issues with backward/forward compatibility. Microsoft does not publish documentation for extending SQL Server Management Studio. There are, however, community blogs and sample code that you may be able to leverage.
>
> Microsoft does not support SQL Server Management Studio installations with SQL Server Management Studio extensions present, so if you have installed SQL Server Management Studio extensions, you may want to remove them before calling Microsoft Customer Support about a SQL Server Management Studio issue.

https://msdn.microsoft.com/en-us/ms174219.aspx

**Comment by martzy13** [comment]
This would be amazing. I flip back and forth between visual studio and SSMS at work quite a bit.

**Comment by gandarez** [comment]
I've been started developing it! Will soon be available for downloading.

**Comment by gandarez** [comment]
You can follow it https://github.com/gandarez/ssms-wakatime

**Comment by maximeduf** [comment]
As of SSMS 18.1 the file structure seems to have changed, I have tried putting the WakaTime folder in : C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\Extensions

and when Starting SSMS I get this message : 
![Wakatime Error Message](https://user-images.githubusercontent.com/8013926/60043392-f961c480-968d-11e9-8d95-142d7d6fc935.JPG)


The problem could be myself as I am very new to SSMS, but I have not found further information on this.

**Comment by gandarez** [comment]
@maximeduf please follow all instructions, probably you didn't run the batch file

https://github.com/gandarez/ssms-wakatime
