### ISSUE TITLE
.wakatime-project file not tracking project in IntelliJ

### ISSUE THREAD

**Issue by lindsaymarkward** [wakatime/wakatime#29]
I have put .wakatime-project files in my project folders containing the project name, but it’s not working as desired.
I now see the projects on my dashboard, but it still logs the time to the “parent” workspace name – e.g. in the screenshot, most of the 3 hours was spent on files in “sphere-yamaha” and “go-ync”.
![screen shot 2015-06-29 at 12 09 33 pm](https://cloud.githubusercontent.com/assets/7665042/8422589/e647c63a-1f20-11e5-8183-1dccdaf2ec78.png)

**Comment by alanhamlett** [comment]
Fixed with e8bd8bba76f95d63b4b8b729013e72f0f27fd61b.
