### ISSUE TITLE
This webpage is not available

### ISSUE THREAD

**Issue by screig** [wakatime/wakatime#30]
This webpage is not available
ERR_CONNECTION_CLOSED
ReloadHide details
The webpage at https://wakatime.com/ might be temporarily down or it may have moved permanently to a new web address.

**Comment by Stephn-R** [comment]
Can you attempt this again? I am not having an issue connecting to it now

**Comment by alanhamlett** [comment]
Was doing database maintenance at that time, closing this issue.
