### ISSUE TITLE
support non-ASCII characters in path to cli.py

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime#32]
When [cli.py](https://github.com/wakatime/wakatime/blob/5ec42393b37bafecfb6037dfa52acd92486985d8/wakatime/cli.py#L14) adds the wakatime folder to `sys.path`, if the abspath contains any non-ASCII characters then an invalid path is added to `sys.path`.

To fix, need to make sure the path is unicode before adding to `sys.path`.

Original issue: wakatime/visualstudio-wakatime#33

Related pull request: wakatime/visualstudio-wakatime#34

Similar to: kennethreitz/requests#2688

**Comment by alanhamlett** [comment]
Probably fixed with 85ab61163211b017596581d262bb7fe90194efed.

**Comment by alanhamlett** [comment]
Still need to fix problem with requests library.

**Comment by shindannin** [comment]
Hi,
As a temporary fix, is it possible to change the path from AppData\Roaming\Microsoft Corporation\Microsoft® Visual Studio® 2015 to ASCII character path by removing ®? Otherwise, Visual Studio user cannot use the add-in. Thanks!

**Comment by alanhamlett** [comment]
If you change your Visual Studio install directory that would work. I'm not sure if removing ® from the path would cause the path to not exist.

Can you paste an error message or python traceback here from your `~/.wakatime.log` file?

**Comment by shindannin** [comment]
Thank you so much for the answers!

> If you change your Visual Studio install directory that would work. 

WakaTime is not under the Visual Studio install directory, so even if I change it to another location, the issue won't be fixed.
- Visual Studio is installed at
     C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe"
- WakaTime is installed at
     C:\Users\My Name\AppData\Roaming\Microsoft Corporation\Microsoft® Visual Studio® 2015\14.0.23107.0


>  I'm not sure if removing ® from the path would cause the path to not exist.

I tried something. It seems if "Microsoft® Visual Studio® 2015" is missing, the new "Microsoft® Visual Studio® 2015" folder is automatically generated when starting VS. Maybe, is the directory name decided by Visual Studio? Hmm,,, it seems hard.


> Can you paste an error message or python traceback here from your ~/.wakatime.log file?

Unfortunately, there is no output in the Wakatime output window on VS. Moreover, ".wakatime.log" is not generated. (I set true to debug in wakatime.cfg.)


I have confirmed python is working in the root. Using Windows 7 and visual studio 2015 professional. Let me know if you need more information.

**Comment by alanhamlett** [comment]
@shindannin can you try with the latest version of wakatime cli? This change might have fixed the problem: afc012ab6361d7d12e1b9519a4b5a3f14c559bd0

To get the latest version, just delete your `wakatime-master` folder in `AppData\Roaming\Microsoft Corporation\Microsoft® Visual Studio® 2015` and restart Visual Studio.

**Comment by shindannin** [comment]
I have just tried it but the change doesn't fix the problem. Just to be sure, I look at certs.py and it has your change afc012a.

**Comment by shindannin** [comment]
Hi,

After the update, I can see an output in VisualStudio 2015 as follows,

[Wakatime Debug 05:46:49 午後] ["C:\Python34\pythonw", "C:\Users\NobuMiu\AppData\Roaming\Microsoft Corporation\Microsoft® Visual Studio® 2015\14.0.23107.0\wakatime-master\wakatime\cli.py", "--key", "********-****-****-****-********124d", "--file", "C:\Users\NobuMiu\Documents\Visual Studio 2008\Projects\topcoder\marathon\tester\marathon87\code\marathon87.cpp", "--plugin", "visualstudio/14.0 visualstudio-wakatime/5.0.8", "--write", "--project", "marathon"]
[Wakatime Debug 05:46:50 午後] CLI STDOUT: 
[Wakatime Debug 05:46:50 午後] CLI STDERR: Traceback (most recent call last):
  File "<encoding error>", line 24, in <module>
ImportError: No module named 'wakatime'

**Comment by shindannin** [comment]
After your update, I can see the log output on Visual Studio 2015, so I have just sent the log to your email address. (wakatime.log is also generated but it is empty.) Could you please check it out?

**Comment by alanhamlett** [comment]
@shindannin I've just pushed another update that should fix your `ImportError`. It was just an addition to 85ab61163211b017596581d262bb7fe90194efed to catch `ImportError` exceptions and try an alternate import method.

Can you try the latest version?

**Comment by shindannin** [comment]
Yes, I tried the latest but it still didn't work. The output log on the VS seems different, so I have just sent an email with it. Could you please have a look? Thanks!

**Comment by alanhamlett** [comment]
I've just pushed another update, 43c461a7cc97da2b7a36db4c75f1e432b8a5b649, to fix the `UnicodeDecodeError` when opening the file with `utf-8` encoding. Can you try the latest version?

**Comment by shindannin** [comment]
Hi I tried the latest but it didn't work. I emailed to you with the log file. Could you look into it? Thanks!

**Comment by alanhamlett** [comment]
@shindannin can you try the latest version?

bba2015d9b6797f8eca94fef6dbd964c27734891 should fix the `TypeError: cafile should be a valid filesystem path` exception. I was able to finally reproduce this on a Windows 8.1 VM and Python 3.4.

Python 2 can't import from folders containing unicode characters, so WakaTime will only work on Windows with Python 3.

**Comment by shindannin** [comment]
Finally it works! Thank you very much for your support!

**Comment by alanhamlett** [comment]
Awesome! I'll close this issue now. Thanks for helping so much through this difficult problem!
