### ISSUE TITLE
C# Language specific leaderboard is showing the wrong language dialects

### ISSUE THREAD

**Issue by rexwhitten** [wakatime/wakatime#34]
Currently the C# Leaderboard shows C and C++ dialects and not C# anymore. this was working as of yesterday. I can provide more details if needed 

C# Leaderboard : https://wakatime.com/leaders?language=C%23

**Comment by alanhamlett** [comment]
Thanks, it's fixed now. I was stripping non-word characters from the cache key :fearful:

**Comment by rexwhitten** [comment]
Thanks a lot! It is working now.
