### ISSUE TITLE
Support for Gitlab

### ISSUE THREAD

**Issue by Lolmewn** [wakatime/wakatime#35]
Gitlab is an open-source git repository users can install on their own servers and is widely used for project hosting, just like github and bitbucket. It would be awesome to be able to see commit statistics after connecting with Gitlab. 

https://about.gitlab.com/features/#community

**Comment by thiagodebastos** [comment]
I'd love for this to happen!

**Comment by RohanSakhale** [comment]
We all would love to see this happen, GitLab provides OAuth2 which can be integrated with each self-hosted GitLab instance. I see a tweet already having a discussion in roll - https://twitter.com/gitlab/status/609080889079791616

GitLab OAuth2 Integration Doc - http://doc.gitlab.com/ce/integration/oauth_provider.html

**Comment by khmelevskii** [comment]
+1

**Comment by toptalo** [comment]
:+1:

**Comment by paperstack** [comment]
yes please

**Comment by mimibar** [comment]
+1

**Comment by Riotherio** [comment]
+1

**Comment by alanhamlett** [comment]
Suppor for GitLab is available now:
https://wakatime.com/integrations
https://wakatime.com/blog/30-connect-your-wakatime-to-gitlab

**Comment by iSDP** [comment]
@alanhamlett can you also add support for private Gitlab instances?

**Comment by alanhamlett** [comment]
@iSDP do you mean self-hosted GitLab? We do support self-hosted GitLab instances as long as the GitLab API for your self-hosted instance can be accessed from the internet.

**Comment by douglance** [comment]
@alanhamlett Would it be possible to add support for `/spent` command from GitLab? https://gitlab.com/help/user/project/time_tracking.md

**Comment by gandarez** [comment]
I created a new issue pelase report there @alanhamlett @douglance
