### ISSUE TITLE
Track time used on individual git branches

### ISSUE THREAD

**Issue by tshtrifork** [wakatime/wakatime#38]
Most of us have experienced that a customer wants us to specify the time used on individual stories/subprojects. This could help with that.

**Comment by alanhamlett** [comment]
We do this already, viewing a project on the website you should see a branch dropdown.
![screen shot 2015-12-10 at 8 32 14 am](https://cloud.githubusercontent.com/assets/522344/11721458/c0e7c44e-9f18-11e5-9619-171e47269817.png)

**Comment by cwilby** [comment]
Having an issue with branches containing slash characters, any reason why those wouldn't show in branch dropdown?

**Comment by alanhamlett** [comment]
No, branch names should show for all characters. I've just tested slash characters and they display fine.
