### ISSUE TITLE
ability to map paths to project names using regexes

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime#43]
We might have to ditch the INI format for JSON to get this done.

**Comment by gandarez** [comment]
@alanhamlett what's the status?

**Comment by alanhamlett** [comment]
We need to find a way to use a regex as the key and value in the `~/.wakatime.cfg` INI file. Maybe we allow regex as keys without `=` because that would break the INI format.

JSON allows escaping keys because they are strings, so we can use a regex as a key in JSON. However, that would require dangerous changes to every plugin.

**Comment by alanhamlett** [comment]
Fixed with 615fa5cdac2c42fbfcd1bfbc6a6b6cace86af301.
