### ISSUE TITLE
C9 - Doesn't ask for API key when installing

### ISSUE THREAD

**Issue by dougwells** [wakatime/wakatime#44]
Love Wakatime.  Glad to see C9 integration.  When following instructions ($ c9 install wakatime), I am not asked for my API key and thus my time will not be tracked.  Thoughts?  Is there a property in a JSON file someone I can manually edit to include my API key?  Any other ideas?

**Comment by alanhamlett** [comment]
Moving this issue to wakatime/c9-wakatime#2
