### ISSUE TITLE
Default config file name is inconsistent

### ISSUE THREAD

**Issue by gergelypolonkai** [wakatime/wakatime#46]
`wakatime --help` says the default config file is `~/.wakatime.conf`, but when I run `wakatime` it says it wants to read `.wakatime.cfg`.

(On a side note, this may go into `~/.config/wakatime.conf` aka `$XDG_CONFIG_USER/wakatime.conf` instead, at least on freedesktop systems).

**Comment by alanhamlett** [comment]
Fixed with dce9d70d48f25a9ec1efa123e5c98f25d746ae46. Thanks!
