### ISSUE TITLE
Error Wakatime 2.0.5 to Wakatime 2.0.6

### ISSUE THREAD

**Issue by jfranciscos4** [wakatime/wakatime#48]
Error Log:

null
org.eclipse.equinox.p2.engine
Error
Sat Apr 30 16:45:30 BRT 2016
An error occurred while collecting items to be installed

org.eclipse.equinox.p2.artifact.repository
Error
Sat Apr 30 16:45:30 BRT 2016
No repository found containing: org.eclipse.update.feature,com.wakatime.eclipse.feature,2.0.6

org.eclipse.equinox.p2.artifact.repository
Error
Sat Apr 30 16:45:30 BRT 2016
No repository found containing: osgi.bundle,com.wakatime.eclipse.plugin,2.0.6

org.eclipse.equinox.p2.engine
Error
Sat Apr 30 16:45:30 BRT 2016
session context was:(profile=epp.package.php, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).

**Comment by alanhamlett** [comment]
The most current version is 3.0.1, can you try installing that version?
