### ISSUE TITLE
Display collapse when I change window height.

### ISSUE THREAD

**Issue by nocotan** [wakatime/wakatime#49]
Collapse the display of side menu in WakaTime dashboard page when I change window height.
(https://wakatime.com/dashboard)

**Comment by alanhamlett** [comment]
Can you provide more details to help us fix it please?

**Comment by nocotan** [comment]
![screenshot 2016-05-10 at 08 43 39](https://cloud.githubusercontent.com/assets/10952293/15131546/de742dc8-168b-11e6-9559-77c53468ea4b.png)


I found a state, such as the attached image.
My browser is Chrome and Firefox.
I ask you for a check.

**Comment by alanhamlett** [comment]
Oh, yes that's known when resizing the window to a large width but small height.

**Comment by nocotan** [comment]
Sorry, I didn't know it.
Thank you for me a reply.
