### ISSUE TITLE
Tracking non-project files

### ISSUE THREAD

**Issue by Tusko** [wakatime/wakatime#50]
Hi @alanhamlett .
Can you remove non-project files in to project's reports [http://awesomescreenshot.com/0675uvwt64](url) ?

I mean separate non-project files, like another project `single files` [http://awesomescreenshot.com/0555uvxed4](url)

P.S. Sorry for my english

**Comment by alanhamlett** [comment]
You can use Custom Rules to move tmp files into their own project. Also, to prevent certain files from being tracked you can exclude them by adding the folder as a regex to your `~/.wakatime.cfg` file. Here is some more info:

https://github.com/wakatime/wakatime#configuring
