### ISSUE TITLE
Changing directory to previous directory using "-" causes wakatime: error: argument --entity is required

### ISSUE THREAD

**Issue by iamaaditya** [wakatime/wakatime#51]
Oh-my-zsh adds alias to "cd -" to just "-". When I use "-" command to goto previous directory I get following error:

$  usage: wakatime [-h] [--entity FILE] [--key KEY] [--write] [--plugin PLUGIN]   
                [--time time] [--lineno LINENO] [--cursorpos CURSORPOS]
                [--entity-type ENTITY_TYPE] [--proxy PROXY]
                [--project PROJECT] [--alternate-project ALTERNATE_PROJECT]
                [--alternate-language ALTERNATE_LANGUAGE]
                [--hostname HOSTNAME] [--disableoffline] [--hidefilenames]
                [--exclude EXCLUDE] [--include INCLUDE] [--extra-heartbeats]
                [--logfile LOGFILE] [--apiurl API_URL] [--timeout TIMEOUT]
                [--config CONFIG] [--verbose] [--version]
wakatime: error: argument --entity is required

**Linux**

Linux <system_name> 4.2.0-16-lowlatency #19-Ubuntu SMP PREEMPT Thu Oct 8 16:19:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.

Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily

**Comment by alanhamlett** [comment]
Moved to wbinglee/zsh-wakatime#10
