### ISSUE TITLE
feat(integration): Consider new settings item, not to send 0 second items in slack integration

### ISSUE THREAD

**Issue by davidgabrichidze** [wakatime/wakatime#52]
e.g. screenshot:
![image](https://cloud.githubusercontent.com/assets/12189125/15720143/2c2b4f28-2844-11e6-918e-ea0704fdadc5.png)

0 second items became duplicated items of github message, w/o expected value from wakatime.

Expected value of wakatime is to report time I have spent on particular task. So, if I have some option in wakatime portal, where I choose not to send 0 second itmes would be great!

**Comment by alanhamlett** [comment]
We can release this in about a week.

**Comment by alanhamlett** [comment]
Released the setting to your Slack integration configuration page:

https://wakatime.com/integrations/slack

**Comment by davidgabrichidze** [comment]
Cool!!! Will test it within work. Thanks

**Comment by gandarez** [comment]
It should come checked as default.

**Comment by alanhamlett** [comment]
It's now default checked.
