### ISSUE TITLE
Vue.js support

### ISSUE THREAD

**Issue by brunjick** [wakatime/wakatime#53]
I just found out that files with .vue extension are from "other" language category. These files contain HTML, Javascript and CSS at the same time, with respective HTML tags, so it can be considered as valid HTML.

PS. I'm using PhpStorm

**Comment by alanhamlett** [comment]
Added support for files ending with `.vue`. Thanks!

**Comment by makmm** [comment]
Actually, it would be cool if it detected if it's html or css or js what's being coded, as .vue files are a mix of those.
