### ISSUE TITLE
Elm files seem to get logged as language other in the stats.

### ISSUE THREAD

**Issue by 7sharp9** [wakatime/wakatime#54]

**Comment by alanhamlett** [comment]
Added in v6.0.5. Which editor are you using? Each one might get the update at different times.

**Comment by 7sharp9** [comment]
This was vscode, and sublime

**Comment by alanhamlett** [comment]
Make sure you're using v7.0.6 of sublime-wakatime and for Vscode just restart the editor and it will check for updates to wakatime-cli.
