### ISSUE TITLE
Time Spend on a project is replaced

### ISSUE THREAD

**Issue by talhajunaidd** [wakatime/wakatime#59]
If a project is opened with one IDE and then same project is opened with some other IDE the project time is replaced with the new time spend with IDE.

I have faced it with VSCODE and IntelliJ IDEA
1st IDE >> VSCODE
2nd IDE >> IntelliJ IDEA
The time spend on the project was replaced with the time spend using IntelliJ IDEA.
The time spend on a single project should be added up from both IDE's

**Comment by alanhamlett** [comment]
I just added a new test case (59871a8bd9ddf32bb22c356954946b5cef449509) that makes sure multiple executions do not overwrite projects. The nature of [heartbeats](https://wakatime.com/faq#what-data-is-logged) is they work with multiple editors seamlessly.

Without a failing test or another way to reproduce this, I don't have any way of fixing it.
