### ISSUE TITLE
Sublime Text 3 problem

### ISSUE THREAD

**Issue by QAQMiao** [wakatime/wakatime#62]
Hello, I'm using WakaTime to record my code time in Sublime Text 3. But here maybe has some problems and the console of python.exe open and close again and again automaticlly. So what can I do to solve this problem?
![image](https://cloud.githubusercontent.com/assets/8213657/18743966/37e7e4fe-80ee-11e6-9bb7-bec245df7a7c.png)

**Comment by alanhamlett** [comment]
It should be trying to run `pythonw.exe` first which doesn't cause the popup window. Try deleting this folder and restarting Sublime Text:
`C:\Users\mengqianye\AppData\Roaming\WakaTime\python\`
