### ISSUE TITLE
project map question

### ISSUE THREAD

**Issue by zchee** [wakatime/wakatime#63]
Sorry, not an issue. just question.
If the wakatime already have another discuss place, sorry again. Please ignore and close it.

I want to migrate the two or more directory to one project.
Yes, I know https://github.com/wakatime/wakatime#configuring. and maybe I can set this config.

However, If I set that config, How change the previous data on wakatime dashboard?
Like, previous data also migrate according to that config or migrate data only after I set.
Also, If only after I set, Is there a way to migrate the previous data?

Thanks.

**Comment by alanhamlett** [comment]
You can rename previous data using `Custom Rules`:
https://wakatime.com/faq#set-project-name

Then once you set the project name using a `.wakatime-project` file or the project map section, you can delete the Custom Rule.

**Comment by zchee** [comment]
@alanhamlett Ah! I was never saw setting page, thanks!
and `.wakatime-project` file is understand, will try it.

Thanks quickly!

**Comment by ArchieT** [comment]
What is the limit on the count of custom rules? It appears to be 99, and for months I have been blindly adding new rules thinking that they will show up later, and they were all apparently immediately truncated without notice :disappointed:  (I'm adding rules ad hoc, and I always wanted not to spend too much time on it, so I always held myself back from thinking about it). I estimate I've lost a few hundred rules that way :stuck_out_tongue_closed_eyes: 
There should be an email sent in case of rules update failure.

**Comment by alanhamlett** [comment]
Deleting old rules just means they won't be applied to any new coding activity, but the changes that old rule made past coding activity are still saved.

Just updated the UI to warn when adding too many rules. Instead of rules, send me an email and I'll help improve language detection.

**Comment by ArchieT** [comment]
Most of my rules are project-related.
My language rules are a bit overdone and sometimes seem to make little sense... My current language-related rules include:
```
.cljc → Clojure    ← that one makes the most sense, CLJC files are shown as "Other"
known_hosts → known_hosts
PKGBUILD → PKGBUILD
gpa.conf → GnuPG conf
gpg.conf → GnuPG conf
gpg-agent.conf → GnuPG conf
.mutt → Muttrc
.Xdefault → Xresources
.i3/config → i3-config
.mailcap → mailcap
.tmux.conf → .tmux.conf
gitconfig → Gitconfig
.i3blocks.conf → i3blocks.conf
.procmailrc → procmailrc
.git/index → git-index
.gp → Gnuplot
.ctags → .ctags
mopidy.conf → mopidy-conf
.mbox → Mail
.sty → TeX
vimrc → VimL
.xprofile → Bash
pacman.conf → pacman.conf
.install → .install
.git/rebase-merge/git-rebase-todo → git-rebase-todo
lighttpd.conf → lighttpd.conf
nsswitch.conf → nsswitch.conf
.hgrc → .hgrc
.hg/hgrc
xorg.conf → xorg.conf
10-synaptics → xorg.conf
.gitignore → .gitignore
.rules →.rules (udev)
resolv.conf → resolv.conf
dhcpd.conf → dhcpd.conf
```
It would be nice if there would be a feature to execute a rule once to apply it to past records,
without keeping it in the settings. How much time do I have to wait to be sure that such a rule has already finished altering past records and I can delete it? Also, it would be nice to only shedule rules on a time range.

**Comment by alanhamlett** [comment]
The project settings could be moved client-side using a `.wakatime-project` file or the `[projectmap]` config section in `~/.wakatime.cfg`. Here's more info:

[.wakatime-project file](https://wakatime.com/faq#rename-projects)
[projectmap config section](https://github.com/wakatime/wakatime/blob/master/wakatime/projects/projectmap.py#L6)

For the languages, common languages should be detected and if they aren't let me know and I'll update the rules. For example, I just added support for these file extensions for all users:
* `cljc`
* `muttrc`
* `tmux.conf`
* `gitconfig`
* `gitignore`
* `mbox`
* `sty`
* `hgrc`
* `vimrc`

The languages ending with `.conf` could be consolidated into one language called `Config` if you don't need to know which type of config file you were editing?

> How much time do I have to wait to be sure that such a rule has already finished altering past records and I can delete it?
The only way to know when a rule has been applied is by refreshing your dashboard and looking for the change.

> It would be nice if there would be a feature to execute a rule once to apply it to past records,
without keeping it in the settings. Also, it would be nice to only shedule rules on a time range.
Great idea, but probably only power-users would find and use it. It might be worth building as a stand-alone feature like the [Code Delete Tool](https://wakatime.com/code-delete-tool).
