### ISSUE TITLE
WakaTime Error appears when API Key not defined

### ISSUE THREAD

**Issue by sean-mcmanus** [wakatime/wakatime#64]
VS Code 1.5.3, WakaTime 1.0.6, Win10. When I open a workspace it says WakaTime Error at the bottom. It may only repro in certain cases.

![wakatimeerror](https://cloud.githubusercontent.com/assets/19859882/18850452/7bddb246-83ec-11e6-950c-653f0c58a449.png)

**Comment by alanhamlett** [comment]
What error message shows when you hover your mouse over the status bar icon?

Are there any errors in your `~/.wakatime.log` file?

**Comment by sean-mcmanus** [comment]
I'm still searching for the wakatime.log, do you know where it is? I'm on Windows so I don't have a ~ directory. I haven't tried on Linux yet.

![wakatimeerror2](https://cloud.githubusercontent.com/assets/19859882/18851391/97ffec1a-83f0-11e6-82c1-340edf361b6d.png)

**Comment by alanhamlett** [comment]
It would be located at `C:\Users\<username>\.wakatime.log`.

**Comment by sean-mcmanus** [comment]
There is no wakatime.log in my entire user's directory. I'm reproing the exact same bug on Linux. No log is written in both cases.

**Comment by sean-mcmanus** [comment]
When I debugging our C/C++ extension I see the errors below:

Current wakatime-core version is 6.0.9
Checking for updates to wakatime-core...
Array[127]
[Guides] Sending usage statistics...
usage: wakatime [-h] [--entity FILE] [--key KEY] [--write] [--plugin PLUGIN]
                [--time time] [--lineno LINENO] [--cursorpos CURSORPOS]
                [--entity-type ENTITY_TYPE] [--proxy PROXY]
                [--project PROJECT] [--alternate-project ALTERNATE_PROJECT]
                [--alternate-language ALTERNATE_LANGUAGE]
                [--hostname HOSTNAME] [--disableoffline] [--hidefilenames]
                [--exclude EXCLUDE] [--include INCLUDE] [--extra-heartbeats]
                [--logfile LOGFILE] [--apiurl API_URL] [--timeout TIMEOUT]
                [--config CONFIG] [--verbose] [--version]
wakatime: error: Missing api key
Error: Could not read from config file C:\Users\seanmcm\.wakatime.cfg
Error: Command failed: \python27\pythonw C:\Users\seanmcm\.vscode\extensions\WakaTime.vscode-wakatime-1.0.6\out\wakatime-master\wakatime\cli.py --file f:\VS\src\vc\designtime\vscode\Microsoft.VSCode.CPP.Extension\Microsoft.VSCode.CPP.Extension\New folder\Test.cpp --plugin vscode/1.5.3 vscode-wakatime/1.0.6 --alternate-project vc

**Comment by sean-mcmanus** [comment]
Entering the API key fixes it :)

**Comment by alanhamlett** [comment]
Fixed with wakatime/vscode-wakatime@6d8f9012dce7bfc62c4af339e6d5b217a7b0951b.
