### ISSUE TITLE
Empty dashboard

### ISSUE THREAD

**Issue by uppermanis** [wakatime/wakatime#65]
I have **empty dashboard** today. I'm using Sublime & Atom. I watched log and found this:

> **ImportError: No module named 'wakatime.dependencies.html'\n"**
> and
> **ImportError: No module named 'wakatime.dependencies.css'\n"**

After day same error. It's realy sad..

an hour later I searching same issue/error here, and find this one: https://github.com/wakatime/wakatime/issues/24#issuecomment-108223682

I try re-install python, and that's work. I hope I can help someone who has / was or will be similar trouble
But my yesterday time was lost, sad.

**Comment by alanhamlett** [comment]
That error message is normal, and only shows when debug mode is turned on. I'll release an update with a more human readable error message.

**Comment by alanhamlett** [comment]
Improved the debug message with 92d8960250c565d645f38e8fde4d61869b366f8b.
