### ISSUE TITLE
Problem after installing WakaTime on NPP

### ISSUE THREAD

**Issue by benyaminl** [wakatime/wakatime#66]
![capture](https://cloud.githubusercontent.com/assets/2817332/19409532/96832190-92ff-11e6-93a5-cd07f1015f0b.PNG)
I'm new in WakaTime, I'm just can't resolve this problem, it always appear when NPP start after installing WakaTime Plugins... when I remove it, this things dissapear. Any Clue?
I tried install the Windows C++ 2015 Runtime Distribution for x86 but no luck anyway..

**Comment by alanhamlett** [comment]
That means your machine needs to be updated. Usually a Windows Service pack update fixes this issue.

**Comment by benyaminl** [comment]
@alanhamlett Yep maybe, I tried to install this https://support.microsoft.com/en-us/kb/2999226 , also the C++ 2015 Runtime VS and it works. I just reinstall windows 7 because windows 10 cause anomalies on the BIOS and can't shutdown. Thanks for the advice. Close this problem, and thanks.
