### ISSUE TITLE
Needed support for reading config location from environment variables.

### ISSUE THREAD

**Issue by MechanisM** [wakatime/wakatime#67]
I just wanna put wakatime config into my ~/.dot folder and in .bashrc set smth like 
`export WAKATIME_CFG=$HOME/.dot/.wakatime.cfg`
Maybe I missed such an option in docs?

**Comment by alanhamlett** [comment]
Fixed with d8f0968c1ae83005460573cf4b38a095427d299f. You can set the config file and log file locations now with this new env variable: `WAKATIME_HOME`.

**Comment by MechanisM** [comment]
Thanks!
