### ISSUE TITLE
Issue in Terminal/Bash Integration

### ISSUE THREAD

**Issue by ghabxph** [wakatime/wakatime#70]
Can somebody here help me troubleshoot this problem?I just followed the guide at https://wakatime.com/help/plugins/terminal under Bash section but after doing all the guide, every time I open my bash, this error always appear:

> usage: wakatime [-h] [--entity FILE] [--key KEY] [--write] [--plugin PLUGIN]
>                 [--time time] [--lineno LINENO] [--cursorpos CURSORPOS]
>                 [--entity-type ENTITY_TYPE] [--proxy PROXY]
>                 [--project PROJECT] [--alternate-project ALTERNATE_PROJECT]
>                 [--alternate-language ALTERNATE_LANGUAGE]
>                 [--hostname HOSTNAME] [--disableoffline] [--hidefilenames]
>                 [--exclude EXCLUDE] [--include INCLUDE] [--extra-heartbeats]
>                 [--logfile LOGFILE] [--apiurl API_URL] [--timeout TIMEOUT]
>                 [--config CONFIG] [--verbose] [--version]
> wakatime: error: argument --entity is required

Wakatime works after 2 or more `clear` command. I guess there is something wrong with the bash-wakatime.sh. I did some chown and chmod 666 on .waka* files: `.wakatime.cfg` `.wakatime.db` and `.wakatime.log`, but still, the error still appears.

Thank you for your help! :)

PS: Already posted this issue on bash-wakatime repo. I'm just looking for help here.
https://github.com/irondoge/bash-wakatime/issues/6

**Comment by alanhamlett** [comment]
The bash-wakatime repo is the right place, so I'll close this duplicate.
