### ISSUE TITLE
Stuck at wakatime initialized

### ISSUE THREAD

**Issue by technbuzz** [wakatime/wakatime#75]
Tried restarting **Visual Studio Code** many times but won't go beyond "Wakatime Initialized" Status

![screenshot](https://content.screencast.com/users/Samiullah1989/folders/Jing/media/219ad479-0f32-4e27-9bb2-9406f08aba9c/2017-02-06_1527.png)

**Comment by technbuzz** [comment]
I solved it using following steps on windows 7

1. Installed python
2. Reinstalled Wakatime

**Comment by alanhamlett** [comment]
Was this happening even after editing a file? It should switch to "WakaTime Active" after first editing a file.

**Comment by technbuzz** [comment]
Yes I worked for more than hours, most of my work went un-tracked :pensive:  as their is no way to add manual tracking and **Wakatime** is only code activity tracker on *VSCODE*

**Comment by alanhamlett** [comment]
Sorry about that, glad it's working now. I don't think Vscode saves logs after restarting the editor right?

**Comment by technbuzz** [comment]
Didn't know about this, Sir @alanhamlett
