### ISSUE TITLE
Wakatime Microsoft Office Addin

### ISSUE THREAD

**Issue by 06needhamt** [wakatime/wakatime#76]
Here I am requesting for a Microsoft Office Addin to be created for Wakatime

**Comment by alanhamlett** [comment]
Thanks, we will update with any progress here.

**Comment by bbrala** [comment]
Hmm, i thought this was included since i saw an office integration. But appearantly not? Any ETA on this, or is there no work being done on this?

**Comment by gandarez** [comment]
The very first version for `Excel` has been added so please guys try it out and post here the results.

https://github.com/wakatime/office-wakatime
