### ISSUE TITLE
.pro files are both Prolog and qmake

### ISSUE THREAD

**Issue by light2yellow** [wakatime/wakatime#78]
Currently .pro files are tracked as Prolog files. But qmake also has .pro extension. Is there a feature request to make the associations customisable? For example as a JSON dict given the recognised languages and a possibility to edit extensions for each recognised language.

**Comment by alanhamlett** [comment]
For now, you can use a custom rule to match .pro files with the correct language:
https://wakatime.com/settings/rules

**Comment by light2yellow** [comment]
Thank you.
