### ISSUE TITLE
Heartbeat API expired SSL certificate

### ISSUE THREAD

**Issue by CaddyDz** [wakatime/wakatime#80]
None of my text editors plugins could connect to **wakatime API**  
It seems that the heartbeat API uses HSTS to force SSL only connection  
However the certificate has expired  
`api.wakatime.com uses an invalid security certificate. The certificate expired on 02/19/2017 04:36 PM. The current time is 02/19/2017 09:25 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE `
[screenshot](https://i.imgur.com/cibXx4T.png)

**Comment by alanhamlett** [comment]
Fixed, thanks!
