### ISSUE TITLE
Colon in URL is not processed correctly in [projectmap] section, raises configparser.DuplicateOptionError

### ISSUE THREAD

**Issue by coldacid** [wakatime/wakatime#83]
I have a number of projectmap rules for websites in my `.wakatime.cfg` file due to the Chrome plugin not providing a way to specify projects for particular URLs. Unfortunately the config parser thinks the colon in `https://` is the key/value separator, and throws with the following trace:

```
Traceback (most recent call last):
  File "C:\Users\ccharabaruk\AppData\Roaming\WakaTime\wakatime-master\wakatime\configs.py", line 48, in parseConfigFile
    configs.readfp(fh)
  File "C:\Python36\lib\configparser.py", line 760, in readfp
    self.read_file(fp, source=filename)
  File "C:\Python36\lib\configparser.py", line 715, in read_file
    self._read(f, source)
  File "C:\Python36\lib\configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from 'C:\\Users\\ccharabaruk\\.wakatime.cfg' [line 20]: option '^https' in section 'projectmap' already exists
```

**Comment by alanhamlett** [comment]
50141ef7b93bab1bc5b68a4e503701e241e3b91e allows colons in project map keys, but the Chrome extension doesn't use the `$HOME/.wakatime.cfg` file so these project map rules still won't work with the Chrome extension.

**Comment by coldacid** [comment]
Damn. Would be nice if the Chrome extension did use it, or at least had the ability to set up mapping and not just exclusions in its own configuration. Thanks for the fix, though!
