### ISSUE TITLE
It's always logging, even when IDE is in minimized

### ISSUE THREAD

**Issue by alirezasharifianzadeh** [wakatime/wakatime#84]
I tried this in Phpstorm and Sublime, It's always logging and increasing the working time, even when I'm not in the IDE, and it's minimized

**Comment by alanhamlett** [comment]
Are other plugins installed in Phpstorm and Sublime besides WakaTime?

If you turn on debug mode, how often and what file is being logged to your `~/.wakatime.log` file and Sublime Console?

[How to turn on Debug Mode](https://github.com/wakatime/sublime-wakatime#troubleshooting)

**Comment by alirezasharifianzadeh** [comment]
I removed all sublime plugins.
I have only package control and WakaTime.
At 10:16 I opened sublime and added 1 line to a file.
It added 5 minutes immediately after opening sublime.
Then I minimized it for 5 minutes ...
Then I back to sublime and removed that line, and it added 5 minutes again!

**Comment by alanhamlett** [comment]
Try changing your Timeout setting in your Preferences to 5 minutes:
https://wakatime.com/settings/preferences

Here's more info about the way WakaTime tracks coding activity using *Heartbeats*:
https://wakatime.com/faq#afk
