### ISSUE TITLE
Wakatime plugin for Jupyter notebook

### ISSUE THREAD

**Issue by abiduzz420** [wakatime/wakatime#87]
I am spending most of my time doing python on jupyter notebook. I would like my coding activity to be quantified, so that I can know if I am meeting my goals as to how many hours I'm putting into learning about ML in python.
I tried to use hydrogen package for atom, but that does not have a good experience

I would want to have a plugin for jupyter notebook.

**Comment by ymkjp** [comment]
I found @Wakatime considered once.
https://twitter.com/projectjupyter/status/651564937307811840

**Comment by mrdeds** [comment]
Any update on this issue?

**Comment by NdagiStanley** [comment]
I also have this question.

**Comment by jackgoh** [comment]
Any update?

**Comment by mubaris** [comment]
Any update?

**Comment by arpitk09** [comment]
You can track your time on jupyter notebooks too Just following these step 👍 
1 Install waka time chrome plugin [WakaTime](https://chrome.google.com/webstore/detail/wakatime/jnbbnacmeggbgdjgaoojpmhdlkkpblgi?hl=en)
2 Paste you api key 
3 Bingo!!

**Comment by abiduzz420** [comment]
Great news! Thanks

**Comment by DostalJ** [comment]
What about making a wakatime package for new [Jupyter Lab](https://github.com/jupyterlab/jupyterlab)?

**Comment by drorata** [comment]
For me, the Chrome plugin, doesn't seem to distinguish between GitHub (or any other site) and Jupyter.

**Comment by arpitk09** [comment]
For this you can do one thing install Chrome Canary for opening jupyter notebook. Install wakatime plugin on Chrome Canary.  For other website use normal chrome.

**Comment by thedeepanshujain** [comment]
You can configure wakatime chrome extension to monitor for only whitelisted sites and add jupyter localhost URL to wakatime list of whitelisted sites. But this is also not that reliable as it also includes your idle time.

**Comment by Destaq** [comment]
How about when using Jupyter Notebook from VS Code?

**Comment by kurianbenoy** [comment]
> How about when using Jupyter Notebook from VS Code?

Wanted for this use case.

**Comment by SongshGeo** [comment]
> How about when using Jupyter Notebook from VS Code?

Wanted for this use case, too.

**Comment by gandarez** [comment]
If you guys use Jupyter Notebook on VSCODE them will get time coding.

**Comment by jobyid** [comment]
Any new on Jupyter Notebook integration or maybe even a DeepNote integration

**Comment by dmrodriqu** [comment]
using the plugin you can whitelist urls and suffix with @@ProjectName

example
http://localhost:8888@@Jupyter

Browser will be the editor, language will be listed as other
