### ISSUE TITLE
Goals confuses C and C++

### ISSUE THREAD

**Issue by yonathanF** [wakatime/wakatime#95]
Bug: goal that is supposed to track hours spent working with C++ projects tries to track C projects 

How to reproduce: 
* wakatime.com/goals
* New Goals
* Select 'in a language'
* Select C++
* provide some time amount and finish

It will create the new goal as C instead of C++ and it will not capture anytime spent with C++ projects (I got WakaTime CLI on my system). I do, however, see C++ on my dashboard on the Languages pie chart.

**Comment by yonathanF** [comment]
Not sure if this is the right place for this issue though. Lmk if I should move it to somewhere else.

**Comment by alanhamlett** [comment]
Thanks for the bug report, it's fixed now!
