### ISSUE TITLE
Offline reporting 

### ISSUE THREAD

**Issue by devgianlu** [wakatime/wakatime#98]
It happened me many times that I was offline while working. Unluckly all this time hasn't been tracked. 

It would be nice if the stats could be tracked offline and submitted to server afterwards.

**Comment by alanhamlett** [comment]
Coding stats should be saved to `~/.wakatime.db` when working offline, then synced next time your online. Which text editor are you using? If it's not saving coding stats when offline then there should be an error message in your `~/.wakatime.log` file.

**Comment by devgianlu** [comment]
I'm facing the issue with Android Studio and also some other editors. The log file is empty and the database file is there. I'll check it's content whenever I can.

**Comment by devgianlu** [comment]
The issue seems to be fixed after I reinstalled the plugin.
